# Generated by Django 5.2.14 on 2026-05-22 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_auditlog_action_alter_auditlog_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(db_index=True, max_length=32, unique=True)),
                ("full_name", models.CharField(max_length=255)),
                ("village", models.CharField(blank=True, default="", max_length=120)),
                ("block", models.CharField(blank=True, default="", max_length=120)),
                ("district", models.CharField(blank=True, default="", max_length=120)),
                ("region", models.CharField(blank=True, default="", max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        limit_choices_to={"role": "supervisor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registered_workers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["supervisor", "is_active"],
                        name="ix_wreg_supervisor_active",
                    ),
                    models.Index(
                        fields=["phone", "is_active"], name="ix_wreg_phone_active"
                    ),
                ],
            },
        ),
    ]
