# Generated by Django 5.2.14 on 2026-05-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_worker_registration"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="requires_review",
            field=models.BooleanField(default=False, help_text="Flagged for ANM review during backfill"),
        ),
    ]
