# Generated by Django 5.2.14 on 2026-05-22 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_requires_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workerregistration",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "supervisor"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registered_workers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
