# Generated by Django 5.2.14 on 2026-05-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_add_fcm_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="estimated_households",
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name="workerregistration",
            name="estimated_households",
            field=models.PositiveIntegerField(default=200),
        ),
    ]
