# Generated by Django 5.2.14 on 2026-05-31 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_user_estimated_households_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("supervisor", "Supervisor"),
                    ("health_worker", "Health worker"),
                    ("referral_partner", "Referral partner"),
                    ("auditor", "Auditor"),
                    ("state_admin", "State Admin"),
                    ("district_officer", "District Health Officer"),
                    ("block_manager", "Block Health Manager"),
                ],
                db_index=True,
                default="health_worker",
                max_length=32,
            ),
        ),
    ]
