# Generated by Django 5.2.14 on 2026-05-31 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("referrals", "0003_alter_referral_patient"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="assigned_doctor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "referral_partner"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_referrals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="doctor_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="referral",
            name="teleconsultation_jitsi_link",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="referral",
            name="teleconsultation_scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
