# Generated by Django 5.2.14 on 2026-05-21 11:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("registry", "0002_household_head_name_household_head_name_hi_and_more"),
        ("risk_engine", "0003_alter_riskassessment_rules_snapshot_mlmodelversion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "local_uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("scheduled_date", models.DateField()),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("within_24h", "Within 24 hours"),
                            ("within_3_days", "Within 3 days"),
                            ("routine", "Routine"),
                        ],
                        default="routine",
                        max_length=20,
                    ),
                ),
                ("is_auto_scheduled", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("missed", "Missed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("completion_notes", models.TextField(blank=True)),
                ("incentive_claimed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followups",
                        to="registry.patient",
                    ),
                ),
                (
                    "triggered_by_assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_followups",
                        to="risk_engine.riskassessment",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="VisitRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "local_uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("visit_date", models.DateField()),
                ("visit_time", models.TimeField(blank=True, null=True)),
                (
                    "condition_observed",
                    models.CharField(
                        choices=[("good", "Good"), ("fair", "Fair"), ("poor", "Poor")],
                        default="good",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("next_visit_date", models.DateField(blank=True, null=True)),
                ("referred_to_phc", models.BooleanField(default=False)),
                ("referral_facility", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "follow_up",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visits",
                        to="followups.followup",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visit_records",
                        to="registry.patient",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visit_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-visit_date"],
            },
        ),
        migrations.AddIndex(
            model_name="followup",
            index=models.Index(
                fields=["worker", "scheduled_date"], name="ix_followup_worker_date"
            ),
        ),
        migrations.AddIndex(
            model_name="followup",
            index=models.Index(
                fields=["patient", "status"], name="ix_followup_patient_status"
            ),
        ),
        migrations.AddIndex(
            model_name="followup",
            index=models.Index(fields=["status"], name="ix_followup_status"),
        ),
        migrations.AddIndex(
            model_name="visitrecord",
            index=models.Index(
                fields=["worker", "visit_date"], name="ix_visit_worker_date"
            ),
        ),
        migrations.AddIndex(
            model_name="visitrecord",
            index=models.Index(
                fields=["patient", "visit_date"], name="ix_visit_patient_date"
            ),
        ),
    ]
