# Generated by Django 5.2.14 on 2026-05-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("followups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="followup",
            name="distance_from_household_m",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="followup",
            name="gps_verification_status",
            field=models.CharField(blank=True, default="not_captured", max_length=20),
        ),
        migrations.AddField(
            model_name="followup",
            name="visit_accuracy_m",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="followup",
            name="visit_gps_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="followup",
            name="visit_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="followup",
            name="visit_lng",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
