# Generated by Django 5.2.14 on 2026-05-22 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("followups", "0002_gps_fields"),
        (
            "registry",
            "0004_patient_anc_visit_count_patient_bank_account_number_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="followup",
            name="bypass_reason",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="followup",
            name="visit_otp_bypassed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="followup",
            name="visit_otp_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="VisitVerificationOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp_hash", models.CharField(max_length=200)),
                ("sent_to_phone", models.CharField(max_length=32)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bypass_reason",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "bypass_approved_by",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "asha_worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registry.patient",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["patient", "asha_worker"],
                        name="ix_visit_otp_patient_worker",
                    )
                ],
            },
        ),
    ]
