# Generated by Django 5.2.14 on 2026-05-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("followups", "0004_backfill_orphaned_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followup",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="followup",
            name="urgency",
            field=models.CharField(
                choices=[
                    ("within_24h", "Within 24 hours"),
                    ("within_3_days", "Within 3 days"),
                    ("routine", "Routine"),
                ],
                db_index=True,
                default="routine",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="visitverificationotp",
            name="expires_at",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="visitverificationotp",
            name="is_used",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
