# Generated by Django 5.2.14 on 2026-05-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("followups", "0008_visitrecord_distance_from_household_m_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitrecord",
            name="gps_verification_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_captured", "Not captured"),
                    ("within_radius", "Within radius"),
                    ("warning_zone", "Warning zone"),
                    ("outside_radius", "Outside radius"),
                    ("no_household_gps", "No household GPS"),
                ],
                default="not_captured",
                max_length=20,
            ),
        ),
    ]
