# Generated by Django 5.2.14 on 2026-05-23 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("followups", "0010_fix_fk_on_delete_user"),
        ("registry", "0006_add_missing_db_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followup",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="followups",
                to="registry.patient",
            ),
        ),
        migrations.AlterField(
            model_name="visitrecord",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visit_records",
                to="registry.patient",
            ),
        ),
        migrations.AlterField(
            model_name="visitverificationotp",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="registry.patient",
            ),
        ),
    ]
