# Generated by Django 5.2.14 on 2026-06-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("followups", "0011_alter_followup_patient_alter_visitrecord_patient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="followup",
            name="visit_state",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled"),
                    ("EN_ROUTE", "En Route"),
                    ("ARRIVED", "Arrived"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("EMERGENCY", "Emergency"),
                    ("DISPATCH_SENT", "Dispatch Sent"),
                    ("REFERRED", "Referred"),
                    ("VERIFIED", "Verified"),
                    ("FLAGGED", "Flagged"),
                    ("REVIEW", "Under Review"),
                    ("SKIPPED", "Skipped"),
                ],
                db_index=True,
                default="SCHEDULED",
                max_length=30,
            ),
        ),
    ]
