# Generated by Django 5.2.14 on 2026-05-21 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["recipient", "created_at"], name="ix_notif_recipient_created"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["channel"], name="ix_notif_channel"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["read_at"], name="ix_notif_read_at"),
        ),
    ]
