# Generated by Django 5.2.14 on 2026-06-02 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("followups", "0012_uber_architecture"),
        ("registry", "0007_patient_abortions_patient_blood_group_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyDispatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("HIGH", "High"),
                            ("MODERATE", "Moderate"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DETECTED", "Detected"),
                            ("DISPATCHING", "Dispatching"),
                            ("ASSIGNED", "Assigned"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("EN_ROUTE", "En Route"),
                            ("ON_SITE", "On Site"),
                            ("RESOLVED", "Resolved"),
                            ("REFERRED", "Referred"),
                            ("ESCALATED", "Escalated"),
                            ("SUPERVISOR_NOTIFIED", "Supervisor Notified"),
                            ("TIMEOUT", "Timeout"),
                        ],
                        db_index=True,
                        default="DETECTED",
                        max_length=30,
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[
                            ("risk_engine", "Risk Engine"),
                            ("asha_manual", "ASHA Manual"),
                            ("sync_late", "Late Sync Detection"),
                            ("supervisor", "Supervisor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("arrived_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("resolved_on_site", "Resolved On Site"),
                            ("referred", "Referred to Facility"),
                            ("false_alarm", "False Alarm"),
                            ("timeout", "Timeout"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "h3_cell_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=16
                    ),
                ),
                ("search_radius_ring", models.PositiveSmallIntegerField(default=1)),
                ("candidates_considered", models.PositiveSmallIntegerField(default=0)),
                ("is_delayed_sync", models.BooleanField(default=False)),
                (
                    "offline_duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatch_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_dispatches",
                        to="registry.household",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emergency_dispatches",
                        to="registry.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["state"], name="idx_dispatch_state"),
                    models.Index(
                        fields=["assigned_worker", "state"],
                        name="idx_dispatch_worker_state",
                    ),
                    models.Index(
                        fields=["household", "-created_at"],
                        name="idx_dispatch_household",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VisitStateLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_state", models.CharField(max_length=30)),
                ("to_state", models.CharField(max_length=30)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_logs",
                        to="followups.followup",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["visit", "timestamp"], name="idx_visit_state_log"
                    )
                ],
            },
        ),
    ]
