import { appSchema, tableSchema } from "@nozbe/watermelondb";

const baseCols = [
  { name: "server_id", type: "string", isOptional: true },
  { name: "is_synced", type: "boolean" },
  { name: "created_at", type: "number" },
  { name: "updated_at", type: "number" },
  { name: "is_deleted", type: "boolean" },
  { name: "is_mock", type: "boolean" },
];

export default appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: "households",
      columns: [
        ...baseCols,
        { name: "household_code", type: "string" },
        { name: "head_of_family", type: "string" },
        { name: "address", type: "string", isOptional: true },
        { name: "village", type: "string", isOptional: true },
        { name: "block", type: "string", isOptional: true },
        { name: "district", type: "string", isOptional: true },
        { name: "gps_lat", type: "number", isOptional: true },
        { name: "gps_lng", type: "number", isOptional: true },
        { name: "total_members", type: "number", isOptional: true },
        { name: "male_count", type: "number", isOptional: true },
        { name: "female_count", type: "number", isOptional: true },
        { name: "children_under5", type: "number", isOptional: true },
        { name: "elderly_above60", type: "number", isOptional: true },
        { name: "has_toilet", type: "boolean", isOptional: true },
        { name: "water_source", type: "string", isOptional: true },
        { name: "is_bpl", type: "boolean", isOptional: true },
        { name: "awc_number", type: "string", isOptional: true },
        { name: "lgd_code", type: "string", isOptional: true },
        { name: "asha_worker_id", type: "string", isOptional: true },
      ],
    }),
    tableSchema({
      name: "patients",
      columns: [
        ...baseCols,
        { name: "patient_code", type: "string" },
        { name: "household_id", type: "string", isOptional: true },
        { name: "name", type: "string" },
        { name: "age", type: "number", isOptional: true },
        { name: "gender", type: "string", isOptional: true },
        { name: "phone", type: "string", isOptional: true },
        { name: "aadhaar_last4", type: "string", isOptional: true },
        { name: "has_diabetes", type: "boolean", isOptional: true },
        { name: "has_hypertension", type: "boolean", isOptional: true },
        { name: "has_tb", type: "boolean", isOptional: true },
        { name: "has_asthma", type: "boolean", isOptional: true },
        { name: "has_heart_disease", type: "boolean", isOptional: true },
        { name: "is_pregnant", type: "boolean", isOptional: true },
        { name: "hospitalized_last_year", type: "boolean", isOptional: true },
        { name: "regular_medicines", type: "boolean", isOptional: true },
        { name: "medicines_name", type: "string", isOptional: true },
        { name: "risk_score", type: "number", isOptional: true },
        { name: "risk_level", type: "string", isOptional: true },
        { name: "last_visited", type: "string", isOptional: true },
        { name: "asha_worker_server_id", type: "string", isOptional: true },
        { name: "date_of_birth", type: "string", isOptional: true },
        { name: "immunization_defaulter", type: "boolean", isOptional: true },
        { name: "latest_weight_for_age_z", type: "number", isOptional: true },
      ],
    }),
    tableSchema({
      name: "mother_records",
      columns: [
        ...baseCols,
        { name: "patient_id", type: "string" },
        { name: "mcts_rch_id_mother", type: "string", isOptional: true },
        { name: "mcts_rch_id_child", type: "string", isOptional: true },
        { name: "mother_aadhaar_last4", type: "string", isOptional: true },
        { name: "child_aadhaar_last4", type: "string", isOptional: true },
        { name: "father_name", type: "string", isOptional: true },
        { name: "lmp_date", type: "string", isOptional: true },
        { name: "edd", type: "string", isOptional: true },
        { name: "gravida", type: "number", isOptional: true },
        { name: "prev_live_births", type: "number", isOptional: true },
        { name: "is_high_risk", type: "boolean", isOptional: true },
        { name: "is_pmmvy_eligible", type: "boolean", isOptional: true },
        { name: "bank_name", type: "string", isOptional: true },
        { name: "bank_account", type: "string", isOptional: true },
        { name: "bank_ifsc", type: "string", isOptional: true },
        { name: "postal_account", type: "string", isOptional: true },
        { name: "identified_delivery_institution", type: "string", isOptional: true },
        { name: "anc_visit_1_json", type: "string", isOptional: true },
        { name: "anc_visit_2_json", type: "string", isOptional: true },
        { name: "anc_visit_3_json", type: "string", isOptional: true },
        { name: "anc_visit_4_json", type: "string", isOptional: true },
        { name: "anc_visit_5_json", type: "string", isOptional: true },
        { name: "tt_injection_1_date", type: "string", isOptional: true },
        { name: "tt_injection_2_date", type: "string", isOptional: true },
        { name: "ifa_tablets_issued", type: "number", isOptional: true },
        { name: "ifa_dates_json", type: "string", isOptional: true },
        { name: "calcium_tablets", type: "boolean", isOptional: true },
        { name: "albendazole_given", type: "boolean", isOptional: true },
        { name: "blood_group", type: "string", isOptional: true },
        { name: "rh_type", type: "string", isOptional: true },
        { name: "hiv_screening_date", type: "string", isOptional: true },
        { name: "hiv_result", type: "string", isOptional: true },
        { name: "syphilis_date", type: "string", isOptional: true },
        { name: "syphilis_result", type: "string", isOptional: true },
        { name: "delivery_date", type: "string", isOptional: true },
        { name: "delivery_place", type: "string", isOptional: true },
        { name: "delivery_type", type: "string", isOptional: true },
        { name: "pregnancy_outcome", type: "string", isOptional: true },
        { name: "birth_weight_kg", type: "number", isOptional: true },
        { name: "child_sex", type: "string", isOptional: true },
        { name: "child_cried_at_birth", type: "boolean", isOptional: true },
        { name: "breastfed_within_1hr", type: "boolean", isOptional: true },
        { name: "vit_k_given", type: "boolean", isOptional: true },
        { name: "birth_registration_no", type: "string", isOptional: true },
        { name: "pnc_day1_json", type: "string", isOptional: true },
        { name: "pnc_day3_json", type: "string", isOptional: true },
        { name: "pnc_day7_json", type: "string", isOptional: true },
        { name: "pnc_week6_json", type: "string", isOptional: true },
        { name: "jsy_registered", type: "boolean", isOptional: true },
        { name: "jsy_payment_received", type: "boolean", isOptional: true },
        { name: "pmmvy_installment_1", type: "boolean", isOptional: true },
        { name: "pmmvy_installment_2", type: "boolean", isOptional: true },
        { name: "pmmvy_installment_3", type: "boolean", isOptional: true },
        { name: "sub_centre_reg_no", type: "string", isOptional: true },
        { name: "fixed_vhsnd_day", type: "string", isOptional: true },
      ],
    }),
    tableSchema({
      name: "anc_visit_records",
      columns: [
        ...baseCols,
        { name: "mother_record_id", type: "string" },
        { name: "visit_number", type: "number" },
        { name: "visit_date", type: "string", isOptional: true },
        { name: "pog_weeks", type: "number", isOptional: true },
        { name: "weight_kg", type: "number", isOptional: true },
        { name: "pulse_rate", type: "number", isOptional: true },
        { name: "bp_systolic", type: "number", isOptional: true },
        { name: "bp_diastolic", type: "number", isOptional: true },
        { name: "pallor", type: "string", isOptional: true },
        { name: "oedema", type: "boolean", isOptional: true },
        { name: "jaundice", type: "boolean", isOptional: true },
        { name: "complaints", type: "string", isOptional: true },
        { name: "fundal_height_cm", type: "number", isOptional: true },
        { name: "lie_presentation", type: "string", isOptional: true },
        { name: "fetal_movements", type: "string", isOptional: true },
        { name: "fetal_heart_rate", type: "number", isOptional: true },
        { name: "hemoglobin_gm", type: "number", isOptional: true },
        { name: "urine_albumin", type: "string", isOptional: true },
        { name: "urine_sugar", type: "string", isOptional: true },
        { name: "ultrasonography_done", type: "boolean", isOptional: true },
        { name: "gdm_screening", type: "boolean", isOptional: true },
        { name: "is_under_pmsma", type: "boolean", isOptional: true },
      ],
    }),
    tableSchema({
      name: "immunization_records",
      columns: [
        ...baseCols,
        { name: "patient_id", type: "string" },
        { name: "mother_record_id", type: "string", isOptional: true },
        { name: "vaccine_name", type: "string" },
        { name: "vaccine_code", type: "string" },
        { name: "scheduled_date", type: "string", isOptional: true },
        { name: "administered_date", type: "string", isOptional: true },
        { name: "is_administered", type: "boolean", isOptional: true },
        { name: "is_missed", type: "boolean", isOptional: true },
        { name: "missed_reason", type: "string", isOptional: true },
        { name: "next_due_date", type: "string", isOptional: true },
        { name: "batch_number", type: "string", isOptional: true },
        { name: "anm_name", type: "string", isOptional: true },
        { name: "site", type: "string", isOptional: true },
        { name: "adverse_event", type: "string", isOptional: true },
      ],
    }),
    tableSchema({
      name: "growth_records",
      columns: [
        ...baseCols,
        { name: "patient_id", type: "string" },
        { name: "recorded_date", type: "string" },
        { name: "age_months", type: "number", isOptional: true },
        { name: "weight_kg", type: "number", isOptional: true },
        { name: "height_cm", type: "number", isOptional: true },
        { name: "muac_cm", type: "number", isOptional: true },
        { name: "weight_for_age_z", type: "number", isOptional: true },
        { name: "height_for_age_z", type: "number", isOptional: true },
        { name: "weight_for_height_z", type: "number", isOptional: true },
        { name: "nutrition_status", type: "string", isOptional: true },
        { name: "recorded_by", type: "string", isOptional: true },
        { name: "awc_number", type: "string", isOptional: true },
      ],
    }),
    tableSchema({
      name: "child_development",
      columns: [
        ...baseCols,
        { name: "patient_id", type: "string" },
        { name: "assessment_date", type: "string" },
        { name: "age_months", type: "number", isOptional: true },
        { name: "milestones_json", type: "string", isOptional: true },
        { name: "warning_signs_json", type: "string", isOptional: true },
        { name: "assessed_by", type: "string", isOptional: true },
        { name: "referral_needed", type: "boolean", isOptional: true },
      ],
    }),
    tableSchema({
      name: "survey_responses",
      columns: [
        ...baseCols,
        { name: "patient_id", type: "string" },
        { name: "asha_worker_server_id", type: "string", isOptional: true },
        { name: "survey_date", type: "string" },
        { name: "visit_type", type: "string", isOptional: true },
        { name: "asha_observation", type: "string", isOptional: true },
        { name: "living_condition", type: "string", isOptional: true },
        { name: "healthcare_access", type: "string", isOptional: true },
        { name: "symptom_fever_json", type: "string", isOptional: true },
        { name: "symptom_cough_json", type: "string", isOptional: true },
        { name: "symptom_breathless_json", type: "string", isOptional: true },
        { name: "symptom_chest_pain_json", type: "string", isOptional: true },
        { name: "symptom_weakness_json", type: "string", isOptional: true },
        { name: "symptom_diarrhea_json", type: "string", isOptional: true },
        { name: "symptom_vomiting_json", type: "string", isOptional: true },
        { name: "serious_severe_breathing", type: "boolean", isOptional: true },
        { name: "serious_chest_pain", type: "boolean", isOptional: true },
        { name: "serious_unable_walk", type: "boolean", isOptional: true },
        { name: "serious_pregnancy_comp", type: "boolean", isOptional: true },
        { name: "chronic_freq_urination", type: "boolean", isOptional: true },
        { name: "chronic_excess_thirst", type: "boolean", isOptional: true },
        { name: "chronic_joint_pain", type: "boolean", isOptional: true },
        { name: "chronic_known_bp_dm", type: "boolean", isOptional: true },
        { name: "comm_cough_2weeks", type: "boolean", isOptional: true },
        { name: "comm_fever_3days", type: "boolean", isOptional: true },
        { name: "comm_infection_wounds", type: "boolean", isOptional: true },
        { name: "comm_contact_sick", type: "boolean", isOptional: true },
        { name: "followup_condition", type: "string", isOptional: true },
        { name: "followup_doctor_visited", type: "boolean", isOptional: true },
        { name: "followup_treatment_started", type: "boolean", isOptional: true },
        { name: "computed_risk_score", type: "number", isOptional: true },
        { name: "computed_risk_level", type: "string", isOptional: true },
        { name: "triggered_factors_json", type: "string", isOptional: true },
        { name: "ml_model_version", type: "string", isOptional: true },
        { name: "is_complete", type: "boolean", isOptional: true },
        { name: "device_id", type: "string", isOptional: true },
        { name: "synced_at", type: "string", isOptional: true },
        { name: "consent_accepted", type: "boolean", isOptional: true },
        { name: "consent_version", type: "string", isOptional: true },
      ],
    }),
    tableSchema({
      name: "follow_ups",
      columns: [
        ...baseCols,
        { name: "patient_id", type: "string" },
        { name: "survey_id", type: "string", isOptional: true },
        { name: "due_date", type: "string" },
        { name: "completed_date", type: "string", isOptional: true },
        { name: "is_completed", type: "boolean", isOptional: true },
        { name: "is_overdue", type: "boolean", isOptional: true },
        { name: "follow_type", type: "string", isOptional: true },
        { name: "outcome", type: "string", isOptional: true },
        { name: "notes", type: "string", isOptional: true },
        { name: "incentive_awarded", type: "boolean", isOptional: true },
      ],
    }),
    tableSchema({
      name: "flags",
      columns: [
        ...baseCols,
        { name: "patient_id", type: "string" },
        { name: "asha_worker_server_id", type: "string", isOptional: true },
        { name: "flag_type", type: "string" },
        { name: "severity", type: "string", isOptional: true },
        { name: "description", type: "string", isOptional: true },
        { name: "is_resolved", type: "boolean", isOptional: true },
        { name: "resolved_at", type: "string", isOptional: true },
        { name: "resolution_notes", type: "string", isOptional: true },
      ],
    }),
    tableSchema({
      name: "referrals",
      columns: [
        ...baseCols,
        { name: "patient_id", type: "string" },
        { name: "provider_name", type: "string", isOptional: true },
        { name: "provider_type", type: "string", isOptional: true },
        { name: "disease_category", type: "string", isOptional: true },
        { name: "referral_date", type: "string", isOptional: true },
        { name: "status", type: "string", isOptional: true },
        { name: "outcome", type: "string", isOptional: true },
        { name: "incentive_awarded", type: "boolean", isOptional: true },
      ],
    }),
    tableSchema({
      name: "incentive_records",
      columns: [
        ...baseCols,
        { name: "action_type", type: "string" },
        { name: "patient_id", type: "string", isOptional: true },
        { name: "reference_id", type: "string", isOptional: true },
        { name: "points", type: "number", isOptional: true },
        { name: "amount_inr", type: "number", isOptional: true },
        { name: "period_date", type: "string", isOptional: true },
        { name: "is_approved", type: "boolean", isOptional: true },
        { name: "approved_at", type: "string", isOptional: true },
        { name: "payment_received", type: "boolean", isOptional: true },
      ],
    }),
  ],
});
