/** Shaasthi Design Moodboard Palette */
export const COLORS = {
  primary: "#416CAF",
  accent: "#5974BD",
  success: "#416CAF",
  warning: "#F7A5BE",
  danger: "#FF0000",
  matriMaBg: "#FFF2F6",
  matriMaCard: "#FFF5F7",
  matriMaAccent: "#E91E63",
  purple: "#5974BD",
  background: "#F5F5F7",
  card: "#FFFFFF",
  border: "#D2CECF",
  textPrimary: "#1A1A2E",
  textSecondary: "#6B6B6B",
  textHint: "#9E9E9E",
  navyLight: "#E8EDF5",
  riskLow: "#416CAF",
  riskMedium: "#F7A5BE",
  riskHigh: "#F7A5BE",
  riskCritical: "#FF0000",
  synced: "#416CAF",
  pending: "#F7A5BE",
  offline: "#FF0000",
  nhm: "#FF0000",
  pmmvy: "#5974BD",
  jsy: "#416CAF",
  /** Moodboard surfaces */
  surface: "#F5F5F7",
  surfaceContainer: "#D9D9D9",
  surfaceContainerLow: "#E8E8E8",
  greetingCard: "#E8EDF5",
  greetingBorder: "#D2CECF",
  syncBannerBg: "#FFF0F5",
  syncBannerBorder: "#F7A5BE",
  syncBannerIcon: "#FF0000",
  tricolorSaffron: "#FF9933",
  tricolorWhite: "#FFFFFF",
  tricolorGreen: "#138808",
  incentivePending: "#FFF0F5",
  incentiveApproved: "#E8EDF5",
  incentivePaid: "#E8F5E9",
};

/** Back-compat with older screens */
export const colors = {
  background: COLORS.background,
  surface: COLORS.card,
  primary: COLORS.primary,
  primaryDark: "#2E5290",
  secondary: COLORS.accent,
  accent: COLORS.accent,
  text: COLORS.textPrimary,
  muted: COLORS.textSecondary,
  border: COLORS.border,
  success: COLORS.success,
  warning: COLORS.warning,
  danger: COLORS.danger,
  info: COLORS.primary,
};
