/** Bilingual string map: Hindi primary, English secondary */
export const STRINGS = {
  APP_NAME: { hi: "मेडिलिफ्ट", en: "MEDILIFT" },
  LOGIN: { hi: "लॉग इन", en: "Login" },
  VERIFY_OTP: { hi: "OTP सत्यापन", en: "Verify OTP" },
  SEND_OTP: { hi: "OTP भेजें", en: "Send OTP" },
  MOBILE_NUMBER: { hi: "मोबाइल नंबर", en: "Mobile Number" },
  ENTER_OTP: { hi: "OTP दर्ज करें", en: "Enter OTP" },
  HOME: { hi: "होम", en: "Home" },
  PATIENTS: { hi: "मरीज", en: "Patients" },
  FOLLOW_UPS: { hi: "फॉलो-अप", en: "Follow-ups" },
  EARNINGS: { hi: "कमाई", en: "Earnings" },
  MY_PATIENTS: { hi: "मेरे मरीज", en: "My Patients" },
  ADD_PATIENT: { hi: "मरीज जोड़ें", en: "Add Patient" },
  NEW_SURVEY: { hi: "नया सर्वे", en: "New Survey" },
  SYNC_NOW: { hi: "सिंक", en: "Sync Now" },
  SYNCING: { hi: "सिंक हो रहा है", en: "Syncing" },
  SYNCED: { hi: "सिंक हो गया", en: "Synced" },
  OFFLINE_MODE: { hi: "ऑफलाइन मोड", en: "Offline Mode" },
  PENDING_SYNC: { hi: "सिंक बाकी", en: "Pending sync" },
  LAST_SYNCED: { hi: "आखरी सिंक", en: "Last synced" },
  SURVEYS_TODAY: { hi: "आज सर्वे", en: "Surveys today" },
  RISK_LEVEL: { hi: "जोखिम स्तर", en: "Risk level" },
  CRITICAL: { hi: "गंभीर", en: "Critical" },
  HIGH: { hi: "उच्च", en: "High" },
  MEDIUM: { hi: "मध्यम", en: "Medium" },
  LOW: { hi: "सामान्य", en: "Low" },
  NORMAL: { hi: "सामान्य", en: "Normal" },
  WEAK: { hi: "कमजोर", en: "Weak" },
  VERY_WEAK: { hi: "बहुत कमजोर", en: "Very weak" },
  CLEAN: { hi: "साफ", en: "Clean" },
  MODERATE: { hi: "ठीक", en: "Moderate" },
  POOR: { hi: "खराब", en: "Poor" },
  EASY: { hi: "आसान", en: "Easy" },
  DIFFICULT: { hi: "मुश्किल", en: "Difficult" },
  PRESENT: { hi: "है", en: "Present" },
  ABSENT: { hi: "नहीं", en: "Absent" },
  YES: { hi: "हां", en: "Yes" },
  NO: { hi: "नहीं", en: "No" },
  SAVE: { hi: "सहेजें", en: "Save" },
  SUBMIT: { hi: "जमा करें", en: "Submit" },
  NEXT: { hi: "आगे", en: "Next" },
  BACK: { hi: "वापस", en: "Back" },
  CANCEL: { hi: "रद्द", en: "Cancel" },
  DONE: { hi: "पूर्ण", en: "Done" },
  NAME: { hi: "नाम", en: "Name" },
  AGE: { hi: "उम्र", en: "Age" },
  GENDER: { hi: "लिंग", en: "Gender" },
  MALE: { hi: "पुरुष", en: "Male" },
  FEMALE: { hi: "महिला", en: "Female" },
  OTHER: { hi: "अन्य", en: "Other" },
  PHONE: { hi: "फोन", en: "Phone" },
  ADDRESS: { hi: "पता", en: "Address" },
  VILLAGE: { hi: "गांव", en: "Village" },
  BLOCK: { hi: "ब्लॉक", en: "Block" },
  DISTRICT: { hi: "जिला", en: "District" },
  HOUSEHOLD: { hi: "परिवार", en: "Household" },
  ADD_HOUSEHOLD: { hi: "परिवार जोड़ें", en: "Add household" },
  SYMPTOMS: { hi: "लक्षण", en: "Symptoms" },
  FEVER: { hi: "बुखार", en: "Fever" },
  COUGH: { hi: "खांसी", en: "Cough" },
  BREATHLESSNESS: { hi: "सांस फूलना", en: "Breathlessness" },
  CHEST_PAIN: { hi: "छाती दर्द", en: "Chest pain" },
  WEAKNESS: { hi: "कमजोरी", en: "Weakness" },
  DIARRHEA: { hi: "दस्त", en: "Diarrhea" },
  SEVERITY: { hi: "गंभीरता", en: "Severity" },
  MILD: { hi: "हल्का", en: "Mild" },
  SEVERE: { hi: "गंभीर", en: "Severe" },
  SERIOUS_CONDITIONS: { hi: "गंभीर स्थिति", en: "Serious conditions" },
  CHRONIC_CONDITIONS: { hi: "जीर्ण रोग", en: "Chronic conditions" },
  COMMUNICABLE_DISEASES: { hi: "संचारी रोग", en: "Communicable diseases" },
  ASHA_OBSERVATION: { hi: "ASHA का अवलोकन", en: "ASHA observation" },
  LIVING_CONDITION: { hi: "रहने की स्थिति", en: "Living condition" },
  HEALTHCARE_ACCESS: { hi: "स्वास्थ्य सेवा पहुंच", en: "Healthcare access" },
  FOLLOW_UP: { hi: "फॉलो-अप", en: "Follow-up" },
  SCHEDULE_FOLLOW_UP: { hi: "फॉलो-अप निर्धारित करें", en: "Schedule follow-up" },
  MARK_DONE: { hi: "पूरा चिह्नित करें", en: "Mark done" },
  IMPROVED: { hi: "बेहतर", en: "Improved" },
  SAME: { hi: "समान", en: "Same" },
  WORSE: { hi: "खराब", en: "Worse" },
  REFERRAL: { hi: "रेफरल", en: "Referral" },
  PROVIDER: { hi: "प्रदाता", en: "Provider" },
  TREATMENT: { hi: "इलाज", en: "Treatment" },
  MY_EARNINGS: { hi: "मेरी कमाई", en: "My earnings" },
  POINTS_EARNED: { hi: "अंक अर्जित", en: "Points earned" },
  PENDING_PAYOUT: { hi: "भुगतान बाकी", en: "Pending payout" },
  BADGES: { hi: "बैज", en: "Badges" },
  MOTHER_REGISTER: { hi: "मातृ रजिस्टर", en: "Mother register" },
  ANC_VISIT: { hi: "ANC भेंट", en: "ANC visit" },
  PNC_VISIT: { hi: "PNC भेंट", en: "PNC visit" },
  HIGH_RISK_PREGNANCY: { hi: "उच्च जोखिम गर्भावस्था", en: "High risk pregnancy" },
  EXPECTED_DELIVERY_DATE: { hi: "प्रसव की संभावित तिथि", en: "Expected delivery date" },
  LAST_MENSTRUAL_PERIOD: { hi: "अंतिम माहवारी", en: "Last menstrual period" },
  DELIVERY_DATE: { hi: "प्रसव तिथि", en: "Delivery date" },
  BIRTH_WEIGHT: { hi: "जन्म वजन", en: "Birth weight" },
  IMMUNIZATION: { hi: "टीकाकरण", en: "Immunization" },
  VACCINE_DUE: { hi: "टीका देय", en: "Vaccine due" },
  VACCINE_GIVEN: { hi: "टीका दिया गया", en: "Vaccine given" },
  VACCINE_MISSED: { hi: "टीका चूका", en: "Vaccine missed" },
  GROWTH_MONITORING: { hi: "विकास निगरानी", en: "Growth monitoring" },
  WEIGHT: { hi: "वजन", en: "Weight" },
  HEIGHT: { hi: "ऊंचाई", en: "Height" },
  NUTRITION_STATUS: { hi: "पोषण स्थिति", en: "Nutrition status" },
  SEVERELY_UNDERWEIGHT: { hi: "गंभीर कुपोषण", en: "Severe malnutrition" },
  MODERATELY_UNDERWEIGHT: { hi: "मध्यम कुपोषण", en: "Moderate malnutrition" },
  MCTS_RCH_ID: { hi: "MCTS/RCH ID", en: "MCTS/RCH ID" },
  JSY_REGISTERED: { hi: "JSY पंजीकृत", en: "JSY registered" },
  PMMVY_ELIGIBLE: { hi: "PMMVY पात्र", en: "PMMVY eligible" },
  IFA_TABLETS: { hi: "IFA गोलियां", en: "IFA tablets" },
  TT_INJECTION: { hi: "TT इंजेक्शन", en: "TT injection" },
  BLOOD_GROUP: { hi: "रक्त समूह", en: "Blood group" },
  HIV_SCREENING: { hi: "HIV जांच", en: "HIV screening" },
  ANTENATAL_CARE: { hi: "प्रसवपूर्व देखभाल", en: "Antenatal care" },
  POSTNATAL_CARE: { hi: "प्रसवोत्तर देखभाल", en: "Postnatal care" },
  BREASTFEEDING: { hi: "स्तनपान", en: "Breastfeeding" },
  COMPLEMENTARY_FEEDING: { hi: "पूरक आहार", en: "Complementary feeding" },
  DEVELOPMENTAL_MILESTONE: { hi: "विकास के पड़ाव", en: "Developmental milestone" },
  WARNING_SIGN: { hi: "चेतावनी संकेत", en: "Warning sign" },
  DANGER_SIGN: { hi: "खतरे का संकेत", en: "Danger sign" },
  FAMILY_PLANNING: { hi: "परिवार नियोजन", en: "Family planning" },
  CONTRACEPTION: { hi: "गर्भनिरोधक", en: "Contraception" },
  BIRTH_SPACING: { hi: "जन्म अंतराल", en: "Birth spacing" },
  CONSENT: { hi: "सहमति", en: "Consent" },
  DATA_SYNC: { hi: "डेटा सिंक", en: "Data sync" },
};

export function t(key) {
  return STRINGS[key] ?? { hi: key, en: key };
}
