# Generated by Django 5.2.14 on 2026-05-21 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="syncevent",
            index=models.Index(fields=["status"], name="ix_sync_event_status"),
        ),
        migrations.AddIndex(
            model_name="syncevent",
            index=models.Index(fields=["received_at"], name="ix_sync_event_received"),
        ),
        migrations.AddIndex(
            model_name="syncevent",
            index=models.Index(fields=["event_type"], name="ix_sync_event_type"),
        ),
    ]
