# Generated by Django 4.2.16 on 2026-05-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AncVisitRecord",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("server_id", models.CharField(blank=True, max_length=36, null=True)),
                ("is_synced", models.BooleanField(default=True)),
                ("created_at", models.BigIntegerField()),
                ("updated_at", models.BigIntegerField()),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_mock", models.BooleanField(default=False)),
                ("mother_record_id", models.CharField(db_index=True, max_length=36)),
                ("visit_number", models.IntegerField(default=1)),
                ("payload_json", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "anc_visit_records",
            },
        ),
        migrations.CreateModel(
            name="ChildDevelopment",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("server_id", models.CharField(blank=True, max_length=36, null=True)),
                ("is_synced", models.BooleanField(default=True)),
                ("created_at", models.BigIntegerField()),
                ("updated_at", models.BigIntegerField()),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_mock", models.BooleanField(default=False)),
                ("patient_id", models.CharField(db_index=True, max_length=36)),
                (
                    "assessment_date",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("payload_json", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "child_development",
            },
        ),
        migrations.CreateModel(
            name="Flag",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("server_id", models.CharField(blank=True, max_length=36, null=True)),
                ("is_synced", models.BooleanField(default=True)),
                ("created_at", models.BigIntegerField()),
                ("updated_at", models.BigIntegerField()),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_mock", models.BooleanField(default=False)),
                ("patient_id", models.CharField(db_index=True, max_length=36)),
                (
                    "asha_worker_server_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=36, null=True
                    ),
                ),
                ("flag_type", models.CharField(blank=True, default="", max_length=64)),
                ("severity", models.CharField(blank=True, max_length=32, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_resolved", models.BooleanField(blank=True, null=True)),
                ("resolved_at", models.CharField(blank=True, max_length=32, null=True)),
                ("resolution_notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "flags",
            },
        ),
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("server_id", models.CharField(blank=True, max_length=36, null=True)),
                ("is_synced", models.BooleanField(default=True)),
                ("created_at", models.BigIntegerField()),
                ("updated_at", models.BigIntegerField()),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_mock", models.BooleanField(default=False)),
                ("patient_id", models.CharField(db_index=True, max_length=36)),
                ("survey_id", models.CharField(blank=True, max_length=36, null=True)),
                ("due_date", models.CharField(blank=True, default="", max_length=32)),
                (
                    "completed_date",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("is_completed", models.BooleanField(blank=True, null=True)),
                ("is_overdue", models.BooleanField(blank=True, null=True)),
                ("follow_type", models.CharField(blank=True, max_length=64, null=True)),
                ("outcome", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("incentive_awarded", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "follow_ups",
            },
        ),
        migrations.CreateModel(
            name="GrowthRecord",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("server_id", models.CharField(blank=True, max_length=36, null=True)),
                ("is_synced", models.BooleanField(default=True)),
                ("created_at", models.BigIntegerField()),
                ("updated_at", models.BigIntegerField()),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_mock", models.BooleanField(default=False)),
                ("patient_id", models.CharField(db_index=True, max_length=36)),
                (
                    "recorded_date",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("age_months", models.IntegerField(blank=True, null=True)),
                ("weight_kg", models.FloatField(blank=True, null=True)),
                ("height_cm", models.FloatField(blank=True, null=True)),
                ("muac_cm", models.FloatField(blank=True, null=True)),
                ("weight_for_age_z", models.FloatField(blank=True, null=True)),
                ("height_for_age_z", models.FloatField(blank=True, null=True)),
                ("weight_for_height_z", models.FloatField(blank=True, null=True)),
                (
                    "nutrition_status",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "recorded_by",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("awc_number", models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                "db_table": "growth_records",
            },
        ),
        migrations.CreateModel(
            name="Household",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("server_id", models.CharField(blank=True, max_length=36, null=True)),
                ("is_synced", models.BooleanField(default=True)),
                ("created_at", models.BigIntegerField()),
                ("updated_at", models.BigIntegerField()),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_mock", models.BooleanField(default=False)),
                (
                    "household_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "head_of_family",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("village", models.CharField(blank=True, max_length=128, null=True)),
                ("block", models.CharField(blank=True, max_length=128, null=True)),
                ("district", models.CharField(blank=True, max_length=128, null=True)),
                ("gps_lat", models.FloatField(blank=True, null=True)),
                ("gps_lng", models.FloatField(blank=True, null=True)),
                ("total_members", models.IntegerField(blank=True, null=True)),
                ("male_count", models.IntegerField(blank=True, null=True)),
                ("female_count", models.IntegerField(blank=True, null=True)),
                ("children_under5", models.IntegerField(blank=True, null=True)),
                ("elderly_above60", models.IntegerField(blank=True, null=True)),
                ("has_toilet", models.BooleanField(blank=True, null=True)),
                (
                    "water_source",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("is_bpl", models.BooleanField(blank=True, null=True)),
                ("awc_number", models.CharField(blank=True, max_length=64, null=True)),
                ("lgd_code", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "asha_worker_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=36, null=True
                    ),
                ),
            ],
            options={
                "db_table": "households",
            },
        ),
        migrations.CreateModel(
            name="ImmunizationRecord",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("server_id", models.CharField(blank=True, max_length=36, null=True)),
                ("is_synced", models.BooleanField(default=True)),
                ("created_at", models.BigIntegerField()),
                ("updated_at", models.BigIntegerField()),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_mock", models.BooleanField(default=False)),
                ("patient_id", models.CharField(db_index=True, max_length=36)),
                (
                    "mother_record_id",
                    models.CharField(blank=True, max_length=36, null=True),
                ),
                (
                    "vaccine_name",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "vaccine_code",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "scheduled_date",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "administered_date",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("is_administered", models.BooleanField(blank=True, null=True)),
                ("is_missed", models.BooleanField(blank=True, null=True)),
                ("missed_reason", models.TextField(blank=True, null=True)),
                (
                    "next_due_date",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("anm_name", models.CharField(blank=True, max_length=128, null=True)),
                ("site", models.CharField(blank=True, max_length=64, null=True)),
                ("adverse_event", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "immunization_records",
            },
        ),
        migrations.CreateModel(
            name="IncentiveRecord",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("server_id", models.CharField(blank=True, max_length=36, null=True)),
                ("is_synced", models.BooleanField(default=True)),
                ("created_at", models.BigIntegerField()),
                ("updated_at", models.BigIntegerField()),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_mock", models.BooleanField(default=False)),
                (
                    "action_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "patient_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=36, null=True
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(blank=True, max_length=36, null=True),
                ),
                ("points", models.IntegerField(blank=True, null=True)),
                ("amount_inr", models.FloatField(blank=True, null=True)),
                ("period_date", models.CharField(blank=True, max_length=32, null=True)),
                ("is_approved", models.BooleanField(blank=True, null=True)),
                ("approved_at", models.CharField(blank=True, max_length=32, null=True)),
                ("payment_received", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "incentive_records",
            },
        ),
        migrations.CreateModel(
            name="MotherRecord",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("server_id", models.CharField(blank=True, max_length=36, null=True)),
                ("is_synced", models.BooleanField(default=True)),
                ("created_at", models.BigIntegerField()),
                ("updated_at", models.BigIntegerField()),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_mock", models.BooleanField(default=False)),
                ("patient_id", models.CharField(db_index=True, max_length=36)),
                ("payload_json", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "mother_records",
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("server_id", models.CharField(blank=True, max_length=36, null=True)),
                ("is_synced", models.BooleanField(default=True)),
                ("created_at", models.BigIntegerField()),
                ("updated_at", models.BigIntegerField()),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_mock", models.BooleanField(default=False)),
                (
                    "patient_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "household_id",
                    models.CharField(blank=True, max_length=36, null=True),
                ),
                ("name", models.CharField(blank=True, default="", max_length=128)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=8, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "aadhaar_last4",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("has_diabetes", models.BooleanField(blank=True, null=True)),
                ("has_hypertension", models.BooleanField(blank=True, null=True)),
                ("has_tb", models.BooleanField(blank=True, null=True)),
                ("has_asthma", models.BooleanField(blank=True, null=True)),
                ("has_heart_disease", models.BooleanField(blank=True, null=True)),
                ("is_pregnant", models.BooleanField(blank=True, null=True)),
                ("hospitalized_last_year", models.BooleanField(blank=True, null=True)),
                ("regular_medicines", models.BooleanField(blank=True, null=True)),
                ("medicines_name", models.TextField(blank=True, null=True)),
                ("risk_score", models.FloatField(blank=True, null=True)),
                ("risk_level", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "last_visited",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "asha_worker_server_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=36, null=True
                    ),
                ),
                (
                    "date_of_birth",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("immunization_defaulter", models.BooleanField(blank=True, null=True)),
                ("latest_weight_for_age_z", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "patients",
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("server_id", models.CharField(blank=True, max_length=36, null=True)),
                ("is_synced", models.BooleanField(default=True)),
                ("created_at", models.BigIntegerField()),
                ("updated_at", models.BigIntegerField()),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_mock", models.BooleanField(default=False)),
                ("patient_id", models.CharField(db_index=True, max_length=36)),
                (
                    "provider_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "provider_type",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "disease_category",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "referral_date",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=32, null=True)),
                ("outcome", models.TextField(blank=True, null=True)),
                ("incentive_awarded", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "referrals",
            },
        ),
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("server_id", models.CharField(blank=True, max_length=36, null=True)),
                ("is_synced", models.BooleanField(default=True)),
                ("created_at", models.BigIntegerField()),
                ("updated_at", models.BigIntegerField()),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_mock", models.BooleanField(default=False)),
                ("patient_id", models.CharField(db_index=True, max_length=36)),
                (
                    "asha_worker_server_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=36, null=True
                    ),
                ),
                (
                    "survey_date",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("payload_json", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "survey_responses",
            },
        ),
    ]
