# Generated by Django 5.2.14 on 2026-05-21 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0002_household_head_name_household_head_name_hi_and_more"),
        ("surveys", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyresponse",
            name="photo_base64",
            field=models.TextField(blank=True, help_text="Optional wound/rash photo in base64"),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="surveyresponse",
            index=models.Index(fields=["patient", "submitted_at"], name="ix_survey_patient_submitted"),
        ),
        migrations.AddIndex(
            model_name="surveyresponse",
            index=models.Index(fields=["local_uuid"], name="ix_survey_local_uuid"),
        ),
        migrations.AddIndex(
            model_name="surveyresponse",
            index=models.Index(fields=["created_by"], name="ix_survey_created_by"),
        ),
        migrations.AddIndex(
            model_name="surveyresponse",
            index=models.Index(fields=["synced_at"], name="ix_survey_synced_at"),
        ),
    ]
