# Generated by Django 5.2.14 on 2026-05-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "surveys",
            "0002_surveyresponse_photo_base64_surveyresponse_synced_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyresponse",
            name="survey_type",
            field=models.CharField(db_index=True, max_length=80),
        ),
    ]
