# Generated by Django 5.2.14 on 2026-05-23 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0006_add_missing_db_indexes"),
        ("surveys", "0003_add_missing_db_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyresponse",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="survey_responses",
                to="registry.patient",
            ),
        ),
    ]
