# Generated by Django 5.2.14 on 2026-05-19 05:17

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "local_uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("client_id", models.CharField(max_length=120)),
                ("event_type", models.CharField(default="upsert", max_length=40)),
                ("model_name", models.CharField(max_length=80)),
                ("object_local_uuid", models.CharField(blank=True, max_length=80)),
                ("payload_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("duplicate", "Duplicate"),
                            ("error", "Error"),
                        ],
                        default="applied",
                        max_length=24,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["client_id", "model_name", "object_local_uuid"],
                        name="sync_syncev_client__64e540_idx",
                    )
                ],
            },
        ),
    ]
