"""MCP-specific risk rules for maternal and child health.
Run ONCE after migration to seed the risk_rules table.

Hard flags trigger immediate referral regardless of score.
Scoring rules contribute to the weighted risk score.
"""

import logging
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "shaasthi_backend.settings")

import django

django.setup()

from risk_engine.models import RiskRule  # noqa: E402

logger = logging.getLogger(__name__)

HARD_FLAG_RULES = [
    {
        "code": "mcp_bleeding_pregnancy",
        "name": "Bleeding during pregnancy",
        "field_path": "survey.answers.bleeding_pregnancy",
        "operator": "truthy",
        "value": {},
        "weight": 100,
        "severity": "critical",
        "flag_type": "maternal_hard_flag",
        "is_hard_flag": True,
        "category": "maternal",
        "hard_flag_message_en": "EMERGENCY — bleeding during pregnancy. Hospital immediately.",
        "hard_flag_message_hi": "आपातकाल — गर्भावस्था में रक्तस्राव। तुरंत अस्पताल।",
        "rule_label_en": "Bleeding during pregnancy",
        "rule_label_hi": "गर्भावस्था में रक्तस्राव",
    },
    {
        "code": "mcp_severe_anaemia",
        "name": "Severe anaemia (Hb < 7)",
        "field_path": "anc.hemoglobin_gms",
        "operator": "less_than",
        "value": {"expected_value": 7.0},
        "weight": 100,
        "severity": "critical",
        "flag_type": "maternal_hard_flag",
        "is_hard_flag": True,
        "category": "maternal",
        "hard_flag_message_en": "Severe anaemia (Hb < 7). Transfusion may be needed. Refer to FRU.",
        "hard_flag_message_hi": "गंभीर खून की कमी (Hb < 7)। FRU तुरंत भेजें।",
        "rule_label_en": "Severe anaemia (Hb < 7 g/dL)",
        "rule_label_hi": "गंभीर एनीमिया (Hb < 7)",
    },
    {
        "code": "mcp_severe_hypertension",
        "name": "Severe hypertension (BP >= 160/110)",
        "field_path": "anc.bp_systolic",
        "operator": "greater_than_or_equal",
        "value": {"expected_value": 160},
        "weight": 100,
        "severity": "critical",
        "flag_type": "maternal_hard_flag",
        "is_hard_flag": True,
        "category": "maternal",
        "hard_flag_message_en": "EMERGENCY — BP >= 160. Eclampsia risk. Hospital immediately.",
        "hard_flag_message_hi": "आपातकाल — BP 160 से ऊपर। FRU तुरंत।",
        "rule_label_en": "Severe hypertension (BP >= 160/110)",
        "rule_label_hi": "गंभीर उच्च रक्तचाप (BP >= 160/110)",
    },
    {
        "code": "mcp_absent_fetal_movements",
        "name": "Absent fetal movements",
        "field_path": "anc.fetal_movements",
        "operator": "equals",
        "value": {"expected_value": "absent"},
        "weight": 100,
        "severity": "critical",
        "flag_type": "maternal_hard_flag",
        "is_hard_flag": True,
        "category": "maternal",
        "hard_flag_message_en": "Absent fetal movements. Possible fetal distress. Immediate USG needed.",
        "hard_flag_message_hi": "भ्रूण की हलचल बंद। तुरंत USG करवाएं।",
        "rule_label_en": "Absent fetal movements",
        "rule_label_hi": "भ्रूण की हलचल बंद",
    },
    {
        "code": "mcp_preterm_labour",
        "name": "Preterm labour (< 37 weeks)",
        "field_path": "survey.answers.preterm_labour_pain",
        "operator": "truthy",
        "value": {},
        "weight": 100,
        "severity": "critical",
        "flag_type": "maternal_hard_flag",
        "is_hard_flag": True,
        "category": "maternal",
        "hard_flag_message_en": "Preterm labour pains (< 37 weeks). Hospital immediately.",
        "hard_flag_message_hi": "समय से पहले प्रसव पीड़ा। तुरंत अस्पताल।",
        "rule_label_en": "Preterm labour (< 37 weeks)",
        "rule_label_hi": "समय से पहले प्रसव पीड़ा",
    },
    {
        "code": "mcp_water_bag_burst",
        "name": "Water bag burst without labour",
        "field_path": "survey.answers.water_bag_burst",
        "operator": "truthy",
        "value": {},
        "weight": 100,
        "severity": "critical",
        "flag_type": "maternal_hard_flag",
        "is_hard_flag": True,
        "category": "maternal",
        "hard_flag_message_en": "Water bag burst. Risk of infection. Hospital immediately.",
        "hard_flag_message_hi": "पानी की थैली फट गई। तुरंत अस्पताल।",
        "rule_label_en": "Water bag burst",
        "rule_label_hi": "पानी की थैली फटना",
    },
    {
        "code": "mcp_eclampsia_triad",
        "name": "Eclampsia triad (headache + blurred vision + swelling)",
        "field_path": "survey.answers.eclampsia_triad",
        "operator": "truthy",
        "value": {},
        "weight": 100,
        "severity": "critical",
        "flag_type": "maternal_hard_flag",
        "is_hard_flag": True,
        "category": "maternal",
        "hard_flag_message_en": "Headache, blurred vision, swelling — possible eclampsia.",
        "hard_flag_message_hi": "सिरदर्द, धुंधली दृष्टि, सूजन — एक्लैम्पसिया का खतरा।",
        "rule_label_en": "Eclampsia danger signs",
        "rule_label_hi": "एक्लैम्पसिया के खतरे के संकेत",
    },
    {
        "code": "mcp_vlbw",
        "name": "Very low birth weight (< 2 kg)",
        "field_path": "patient.birth_weight_kg",
        "operator": "less_than",
        "value": {"expected_value": 2.0},
        "weight": 100,
        "severity": "critical",
        "flag_type": "child_hard_flag",
        "is_hard_flag": True,
        "category": "child",
        "hard_flag_message_en": "Birth weight < 2 kg. Needs Kangaroo Mother Care. Refer to SNCU.",
        "hard_flag_message_hi": "जन्म वजन 2 kg से कम। SNCU भेजें।",
        "rule_label_en": "Very low birth weight (< 2 kg)",
        "rule_label_hi": "बहुत कम जन्म वजन (< 2 kg)",
    },
    {
        "code": "mcp_newborn_convulsions",
        "name": "Newborn convulsions",
        "field_path": "pnc.baby_convulsions",
        "operator": "truthy",
        "value": {},
        "weight": 100,
        "severity": "critical",
        "flag_type": "critical_hard_flag",
        "is_hard_flag": True,
        "category": "critical",
        "hard_flag_message_en": "Newborn convulsions. Emergency — call 108.",
        "hard_flag_message_hi": "नवजात को दौरे। आपातकाल — 108 कॉल करें।",
        "rule_label_en": "Newborn convulsions",
        "rule_label_hi": "नवजात को दौरे",
    },
    {
        "code": "mcp_sam",
        "name": "Severe acute malnutrition (below -3SD)",
        "field_path": "growth.nutritional_status",
        "operator": "equals",
        "value": {"expected_value": "severe_underweight"},
        "weight": 100,
        "severity": "critical",
        "flag_type": "child_hard_flag",
        "is_hard_flag": True,
        "category": "child",
        "hard_flag_message_en": "Severe acute malnutrition. Refer to NRC immediately.",
        "hard_flag_message_hi": "गंभीर कुपोषण। NRC तुरंत भेजें।",
        "rule_label_en": "Severe acute malnutrition (below -3SD)",
        "rule_label_hi": "गंभीर कुपोषण (-3SD से नीचे)",
    },
    {
        "code": "mcp_dev_warning_sign",
        "name": "Development warning sign",
        "field_path": "milestone.any_warning_sign",
        "operator": "truthy",
        "value": {},
        "weight": 100,
        "severity": "critical",
        "flag_type": "child_hard_flag",
        "is_hard_flag": True,
        "category": "child",
        "hard_flag_message_en": "Developmental warning sign. Refer to developmental clinic.",
        "hard_flag_message_hi": "विकास में रुकावट। विकास क्लिनिक भेजें।",
        "rule_label_en": "Developmental warning sign",
        "rule_label_hi": "विकास में रुकावट",
    },
]

SCORING_RULES = [
    # Maternal scoring rules
    {
        "code": "mcp_low_anc_visits",
        "name": "Low ANC visit count (< 4)",
        "field_path": "patient.anc_visit_count",
        "operator": "less_than",
        "value": {"expected_value": 4},
        "weight": 3,
        "severity": "medium",
        "flag_type": "maternal_risk",
        "category": "maternal",
        "rule_label_en": "Low ANC visits (< 4 completed)",
        "rule_label_hi": "कम ANC विज़िट (4 से कम)",
    },
    {
        "code": "mcp_low_hemoglobin",
        "name": "Low haemoglobin (< 10 g/dL)",
        "field_path": "anc.hemoglobin_gms",
        "operator": "less_than",
        "value": {"expected_value": 10.0},
        "weight": 3,
        "severity": "medium",
        "flag_type": "maternal_risk",
        "category": "maternal",
        "rule_label_en": "Low haemoglobin (Hb < 10 g/dL)",
        "rule_label_hi": "कम हीमोग्लोबिन (Hb < 10)",
    },
    {
        "code": "mcp_moderate_anaemia",
        "name": "Moderate anaemia (Hb 7-10)",
        "field_path": "anc.hemoglobin_gms",
        "operator": "less_than",
        "value": {"expected_value": 11.0},
        "weight": 2,
        "severity": "medium",
        "flag_type": "maternal_risk",
        "category": "maternal",
        "rule_label_en": "Moderate anaemia (Hb 7-10 g/dL)",
        "rule_label_hi": "मध्यम एनीमिया (Hb 7-10)",
    },
    {
        "code": "mcp_high_bp",
        "name": "High BP (systolic >= 140)",
        "field_path": "anc.bp_systolic",
        "operator": "greater_than_or_equal",
        "value": {"expected_value": 140},
        "weight": 3,
        "severity": "high",
        "flag_type": "maternal_risk",
        "category": "maternal",
        "rule_label_en": "High blood pressure (BP >= 140 systolic)",
        "rule_label_hi": "उच्च रक्तचाप (BP >= 140)",
    },
    {
        "code": "mcp_proteinuria",
        "name": "Urine albumin positive",
        "field_path": "anc.urine_albumin",
        "operator": "equals",
        "value": {"expected_value": "positive"},
        "weight": 2,
        "severity": "high",
        "flag_type": "maternal_risk",
        "category": "maternal",
        "rule_label_en": "Urine albumin positive",
        "rule_label_hi": "मूत्र में एल्ब्यूमिन पॉजिटिव",
    },
    {
        "code": "mcp_oedema",
        "name": "Oedema present",
        "field_path": "anc.oedema",
        "operator": "equals",
        "value": {"expected_value": "present"},
        "weight": 2,
        "severity": "high",
        "flag_type": "maternal_risk",
        "category": "maternal",
        "rule_label_en": "Oedema present",
        "rule_label_hi": "सूजन मौजूद",
    },
    {
        "code": "mcp_reduced_fetal_movements",
        "name": "Reduced fetal movements",
        "field_path": "anc.fetal_movements",
        "operator": "equals",
        "value": {"expected_value": "reduced"},
        "weight": 3,
        "severity": "high",
        "flag_type": "maternal_risk",
        "category": "maternal",
        "rule_label_en": "Reduced fetal movements",
        "rule_label_hi": "भ्रूण की हलचल कम",
    },
    {
        "code": "mcp_gdm_positive",
        "name": "GDM positive",
        "field_path": "anc.gdm_screening",
        "operator": "equals",
        "value": {"expected_value": "positive"},
        "weight": 2,
        "severity": "medium",
        "flag_type": "maternal_risk",
        "category": "maternal",
        "rule_label_en": "Gestational diabetes positive",
        "rule_label_hi": "गर्भकालीन मधुमेह पॉजिटिव",
    },
    {
        "code": "mcp_teen_pregnancy",
        "name": "Teen pregnancy (age < 18)",
        "field_path": "patient.age_years",
        "operator": "less_than",
        "value": {"expected_value": 18},
        "weight": 3,
        "severity": "high",
        "flag_type": "maternal_risk",
        "category": "maternal",
        "rule_label_en": "Teen pregnancy (mother < 18 years)",
        "rule_label_hi": "किशोरी गर्भावस्था (माँ < 18 वर्ष)",
    },
    {
        "code": "mcp_advanced_maternal_age",
        "name": "Advanced maternal age (> 35)",
        "field_path": "patient.age_years",
        "operator": "greater_than",
        "value": {"expected_value": 35},
        "weight": 2,
        "severity": "medium",
        "flag_type": "maternal_risk",
        "category": "maternal",
        "rule_label_en": "Advanced maternal age (> 35 years)",
        "rule_label_hi": "अधिक मातृ आयु (> 35 वर्ष)",
    },
    {
        "code": "mcp_high_gravida",
        "name": "High gravida (>= 4)",
        "field_path": "patient.gravida",
        "operator": "greater_than_or_equal",
        "value": {"expected_value": 4},
        "weight": 2,
        "severity": "medium",
        "flag_type": "maternal_risk",
        "category": "maternal",
        "rule_label_en": "High gravida (G >= 4)",
        "rule_label_hi": "अधिक गर्भधारण (G >= 4)",
    },
    {
        "code": "mcp_prev_cs",
        "name": "Previous C-section",
        "field_path": "patient.obstetric_complications",
        "operator": "contains",
        "value": {"expected_value": "LSCS"},
        "weight": 2,
        "severity": "medium",
        "flag_type": "maternal_risk",
        "category": "maternal",
        "rule_label_en": "Previous C-section delivery",
        "rule_label_hi": "पिछला सिजेरियन प्रसव",
    },
    {
        "code": "mcp_registered_late",
        "name": "Late registration (> 12 weeks)",
        "field_path": "patient.anc_visit_count",
        "operator": "less_than",
        "value": {"expected_value": 1},
        "weight": 1,
        "severity": "low",
        "flag_type": "maternal_risk",
        "category": "maternal",
        "rule_label_en": "Late ANC registration (after 12 weeks)",
        "rule_label_hi": "देर से ANC पंजीकरण (12 सप्ताह के बाद)",
    },
    # Child scoring rules
    {
        "code": "mcp_low_birth_weight",
        "name": "Low birth weight (< 2.5 kg)",
        "field_path": "patient.birth_weight_kg",
        "operator": "less_than",
        "value": {"expected_value": 2.5},
        "weight": 4,
        "severity": "high",
        "flag_type": "child_risk",
        "category": "child",
        "rule_label_en": "Low birth weight (< 2.5 kg)",
        "rule_label_hi": "कम जन्म वजन (< 2.5 kg)",
    },
    {
        "code": "mcp_low_wfa_z",
        "name": "Low weight-for-age Z-score (< -2)",
        "field_path": "growth.wfa_z_score",
        "operator": "less_than",
        "value": {"expected_value": -2.0},
        "weight": 3,
        "severity": "high",
        "flag_type": "child_risk",
        "category": "child",
        "rule_label_en": "Underweight (WFA Z-score < -2 SD)",
        "rule_label_hi": "कम वजन (WFA Z-score < -2 SD)",
    },
    {
        "code": "mcp_missed_vaccines",
        "name": "Missed vaccines (> 0)",
        "field_path": "patient.missed_vaccine_count",
        "operator": "greater_than",
        "value": {"expected_value": 0},
        "weight": 2,
        "severity": "medium",
        "flag_type": "child_risk",
        "category": "child",
        "rule_label_en": "Missed vaccinations",
        "rule_label_hi": "छूटे हुए टीके",
    },
    {
        "code": "mcp_weight_faltering",
        "name": "Weight faltering (not gaining)",
        "field_path": "growth.is_faltering",
        "operator": "truthy",
        "value": {},
        "weight": 2,
        "severity": "medium",
        "flag_type": "child_risk",
        "category": "child",
        "rule_label_en": "Weight faltering (not gaining weight)",
        "rule_label_hi": "वजन नहीं बढ़ रहा",
    },
    {
        "code": "mcp_low_muac",
        "name": "Low MUAC (< 12.5 cm)",
        "field_path": "growth.muac_cm",
        "operator": "less_than",
        "value": {"expected_value": 12.5},
        "weight": 3,
        "severity": "high",
        "flag_type": "child_risk",
        "category": "child",
        "rule_label_en": "Low MUAC (< 12.5 cm)",
        "rule_label_hi": "कम MUAC (< 12.5 cm)",
    },
    {
        "code": "mcp_baby_jaundice",
        "name": "Baby jaundice present",
        "field_path": "pnc.baby_jaundice",
        "operator": "truthy",
        "value": {},
        "weight": 2,
        "severity": "medium",
        "flag_type": "child_risk",
        "category": "child",
        "rule_label_en": "Baby jaundice present",
        "rule_label_hi": "शिशु को पीलिया",
    },
    {
        "code": "mcp_baby_poor_sucking",
        "name": "Baby poor sucking",
        "field_path": "pnc.baby_sucking",
        "operator": "equals",
        "value": {"expected_value": "poor"},
        "weight": 2,
        "severity": "medium",
        "flag_type": "child_risk",
        "category": "child",
        "rule_label_en": "Poor breastfeeding / sucking",
        "rule_label_hi": "कम दूध पीना",
    },
]


def seed_mcp_rules():
    created = 0
    skipped = 0

    for rule_data in HARD_FLAG_RULES + SCORING_RULES:
        code = rule_data["code"]
        _, was_created = RiskRule.objects.update_or_create(
            code=code,
            defaults={
                **rule_data,
                "is_active": True,
                "version": 1,
            },
        )
        if was_created:
            created += 1
        else:
            skipped += 1

    logger.info("✅ Seeded %d new MCP risk rules (%d already existed)", created, skipped)
    print(f"✅ Seeded {created} new MCP risk rules ({skipped} already existed)")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    seed_mcp_rules()
