# Generated by Django 5.2.14 on 2026-05-21 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incentives", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="incentiveledgerentry",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("survey_completion", "Survey completion"),
                    ("high_risk_identification", "High risk identification"),
                    ("hard_flag_referral", "Hard flag referral"),
                    ("followup_completed_on_time", "Follow-up completed on time"),
                    ("followup_missed", "Follow-up missed"),
                    ("anc_registration", "ANC registration"),
                ],
                default="survey_completion",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="incentiveledgerentry",
            name="amount_paise",
            field=models.PositiveIntegerField(default=0, help_text="Amount in paise (rupees × 100)"),
        ),
        migrations.AddField(
            model_name="incentiveledgerentry",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incentiveledgerentry",
            name="approved_by",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="incentiveledgerentry",
            name="description_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="incentiveledgerentry",
            name="description_hi",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="incentiveledgerentry",
            name="month_year",
            field=models.CharField(blank=True, db_index=True, help_text="e.g. 2026-05", max_length=7),
        ),
        migrations.AddField(
            model_name="incentiveledgerentry",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incentiveledgerentry",
            name="reference_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incentiveledgerentry",
            name="reference_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="incentiveledgerentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("paid", "Paid"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="incentiveledgerentry",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("quality", "Quality milestone"),
                    ("training", "Training"),
                    ("transport", "Transport support"),
                    ("supplies", "Supplies"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="incentiveledgerentry",
            index=models.Index(fields=["worker", "month_year"], name="ix_incentive_worker_month"),
        ),
        migrations.AddIndex(
            model_name="incentiveledgerentry",
            index=models.Index(fields=["status"], name="ix_incentive_status"),
        ),
    ]
