# Generated by Django 5.2.14 on 2026-05-23 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incentives", "0002_incentiveledgerentry_activity_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="incentiveledgerentry",
            name="worker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incentive_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
