# Generated by Django 5.2.14 on 2026-05-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentives", "0003_fix_fk_on_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncentiveRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("survey_completion", "Survey completion"),
                            ("high_risk_identification", "High risk identification"),
                            ("hard_flag_referral", "Hard flag referral"),
                            (
                                "followup_completed_on_time",
                                "Follow-up completed on time",
                            ),
                            ("followup_missed", "Follow-up missed"),
                            ("anc_registration", "ANC registration"),
                        ],
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "amount_paise",
                    models.PositiveIntegerField(
                        help_text="Amount in paise (rupees × 100)"
                    ),
                ),
                ("label_en", models.CharField(blank=True, max_length=120)),
                ("label_hi", models.CharField(blank=True, max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Incentive Rate",
                "verbose_name_plural": "Incentive Rates",
                "ordering": ["activity_type"],
            },
        ),
    ]
