# Generated by Django 5.2.14 on 2026-05-28 17:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("incentives", "0006_add_goi_2025_26_activity_types_and_asha_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ashaworkerprofile",
            options={
                "ordering": ["asha_id"],
                "verbose_name": "ASHA Worker Profile",
                "verbose_name_plural": "ASHA Worker Profiles",
            },
        ),
    ]
