# Generated by Django 5.2.14 on 2026-05-21 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flagging", "0001_initial"),
        ("registry", "0003_alter_household_block_alter_household_district_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="flag",
            index=models.Index(
                fields=["patient", "status"], name="ix_flag_patient_status"
            ),
        ),
        migrations.AddIndex(
            model_name="flag",
            index=models.Index(fields=["flag_type"], name="ix_flag_type"),
        ),
        migrations.AddIndex(
            model_name="flag",
            index=models.Index(fields=["severity"], name="ix_flag_severity"),
        ),
        migrations.AddIndex(
            model_name="flag",
            index=models.Index(fields=["source"], name="ix_flag_source"),
        ),
    ]
