"""Seed NHM-aligned default risk rules. Run once after migration: python manage.py seed_risk_rules"""

from django.core.management.base import BaseCommand

from risk_engine.models import RiskRule

DEFAULT_RULES = [
    # ── Hard flags (emergency) ──
    {
        "code": "HF_UNCONSCIOUS",
        "name": "Unconscious / unresponsive",
        "field_path": "survey.answers.unconscious",
        "operator": RiskRule.Operator.TRUTHY,
        "weight": 10,
        "is_hard_flag": True,
        "category": RiskRule.Category.CRITICAL,
        "rule_label_en": "Unconscious / unresponsive",
        "rule_label_hi": "बेहोशी / अनुत्तरदायी",
        "hard_flag_message_en": "EMERGENCY — Patient unresponsive. Call 108 immediately.",
        "hard_flag_message_hi": "आपातकाल — रोगी बेहोश है। तुरंत 108 कॉल करें।",
        "severity": "high",
        "flag_type": "emergency",
    },
    {
        "code": "HF_CONVULSIONS",
        "name": "Convulsions / seizures",
        "field_path": "survey.answers.convulsions",
        "operator": RiskRule.Operator.TRUTHY,
        "weight": 10,
        "is_hard_flag": True,
        "category": RiskRule.Category.CRITICAL,
        "rule_label_en": "Convulsions / seizures",
        "rule_label_hi": "दौरे",
        "hard_flag_message_en": "EMERGENCY — Convulsions observed. Refer to hospital immediately.",
        "hard_flag_message_hi": "आपातकाल — दौरे पड़ रहे हैं। तुरंत अस्पताल भेजें।",
        "severity": "high",
        "flag_type": "emergency",
    },
    {
        "code": "HF_SEVERE_BREATH",
        "name": "Severe breathlessness",
        "field_path": "survey.answers.breathlessness_severity",
        "operator": RiskRule.Operator.EQ,
        "value": {"value": "severe"},
        "weight": 10,
        "is_hard_flag": True,
        "category": RiskRule.Category.CRITICAL,
        "rule_label_en": "Severe breathlessness",
        "rule_label_hi": "गंभीर सांस की तकलीफ",
        "hard_flag_message_en": "EMERGENCY — Severe respiratory distress. Refer immediately.",
        "hard_flag_message_hi": "आपातकाल — गंभीर सांस की तकलीफ। तुरंत रेफर करें।",
        "severity": "high",
        "flag_type": "emergency",
    },
    {
        "code": "HF_FETAL_MOVEMENT",
        "name": "Reduced fetal movement",
        "field_path": "survey.answers.reduced_fetal_movement",
        "operator": RiskRule.Operator.TRUTHY,
        "weight": 4,
        "is_hard_flag": True,
        "category": RiskRule.Category.MATERNAL,
        "rule_label_en": "Reduced fetal movement",
        "rule_label_hi": "भ्रूण की कम हलचल",
        "hard_flag_message_en": "Reduced fetal movement — refer to CHC immediately.",
        "hard_flag_message_hi": "भ्रूण की कम हलचल — तुरंत CHC रेफर करें।",
        "severity": "high",
        "flag_type": "maternal_emergency",
    },
    {
        "code": "HF_VAGINAL_BLEEDING",
        "name": "Vaginal bleeding during pregnancy",
        "field_path": "survey.answers.vaginal_bleeding",
        "operator": RiskRule.Operator.TRUTHY,
        "weight": 10,
        "is_hard_flag": True,
        "category": RiskRule.Category.MATERNAL,
        "rule_label_en": "Vaginal bleeding during pregnancy",
        "rule_label_hi": "गर्भावस्था में योनि से रक्तस्राव",
        "hard_flag_message_en": "EMERGENCY — Vaginal bleeding. Refer to facility immediately.",
        "hard_flag_message_hi": "आपातकाल — योनि से रक्तस्राव। तुरंत अस्पताल भेजें।",
        "severity": "high",
        "flag_type": "maternal_emergency",
    },
    {
        "code": "HF_SEVERE_DEHYDRATION",
        "name": "Severe dehydration with diarrhea",
        "field_path": "survey.answers.severe_dehydration",
        "operator": RiskRule.Operator.TRUTHY,
        "weight": 10,
        "is_hard_flag": True,
        "category": RiskRule.Category.CRITICAL,
        "rule_label_en": "Severe dehydration with diarrhea",
        "rule_label_hi": "दस्त के साथ गंभीर निर्जलीकरण",
        "hard_flag_message_en": "EMERGENCY — Severe dehydration. Start ORS and refer immediately.",
        "hard_flag_message_hi": "आपातकाल — गंभीर निर्जलीकरण। ORS शुरू करें और तुरंत रेफर करें।",
        "severity": "high",
        "flag_type": "emergency",
    },
    # ── Communicable ──
    {
        "code": "FEVER_ACTIVE",
        "name": "Active fever",
        "field_path": "survey.answers.fever",
        "operator": RiskRule.Operator.TRUTHY,
        "weight": 3,
        "category": RiskRule.Category.COMMUNICABLE,
        "rule_label_en": "Active fever",
        "rule_label_hi": "सक्रिय बुखार",
    },
    {
        "code": "COUGH_TB_2W",
        "name": "Cough >= 2 weeks (TB indicator)",
        "field_path": "survey.answers.cough_duration_weeks",
        "operator": RiskRule.Operator.GTE,
        "value": {"value": 2},
        "weight": 4,
        "category": RiskRule.Category.COMMUNICABLE,
        "rule_label_en": "Cough >= 2 weeks (TB indicator)",
        "rule_label_hi": "2 सप्ताह से अधिक खांसी (TB संकेतक)",
    },
    {
        "code": "CONTACT_TB",
        "name": "Contact with known TB patient",
        "field_path": "survey.answers.comm_contact_sick",
        "operator": RiskRule.Operator.TRUTHY,
        "weight": 3,
        "category": RiskRule.Category.COMMUNICABLE,
        "rule_label_en": "Contact with known TB/infectious patient",
        "rule_label_hi": "TB/संक्रामक रोगी से संपर्क",
    },
    {
        "code": "INFECTION_WOUNDS",
        "name": "Active infection / non-healing wounds",
        "field_path": "survey.answers.comm_infection_wounds",
        "operator": RiskRule.Operator.TRUTHY,
        "weight": 3,
        "category": RiskRule.Category.COMMUNICABLE,
        "rule_label_en": "Active infection / non-healing wounds",
        "rule_label_hi": "सक्रिय संक्रमण / न भरने वाले घाव",
    },
    # ── Chronic / NCD ──
    {
        "code": "DIABETES_KNOWN",
        "name": "Known diabetes",
        "field_path": "patient.metadata.diabetes",
        "operator": RiskRule.Operator.TRUTHY,
        "weight": 3,
        "category": RiskRule.Category.CHRONIC,
        "rule_label_en": "Known diabetes",
        "rule_label_hi": "मधुमेह",
    },
    {
        "code": "HYPERTENSION_KNOWN",
        "name": "Known hypertension",
        "field_path": "patient.metadata.hypertension",
        "operator": RiskRule.Operator.TRUTHY,
        "weight": 3,
        "category": RiskRule.Category.CHRONIC,
        "rule_label_en": "Known hypertension",
        "rule_label_hi": "उच्च रक्तचाप",
    },
    {
        "code": "BP_SYS_HIGH",
        "name": "High systolic BP (>140)",
        "field_path": "survey.answers.blood_pressure_sys",
        "operator": RiskRule.Operator.GT,
        "value": {"value": 140},
        "weight": 3,
        "category": RiskRule.Category.CHRONIC,
        "rule_label_en": "High systolic BP (>140)",
        "rule_label_hi": "उच्च सिस्टोलिक BP (>140)",
    },
    {
        "code": "BP_DIA_HIGH",
        "name": "High diastolic BP (>90)",
        "field_path": "survey.answers.blood_pressure_dia",
        "operator": RiskRule.Operator.GT,
        "value": {"value": 90},
        "weight": 3,
        "category": RiskRule.Category.CHRONIC,
        "rule_label_en": "High diastolic BP (>90)",
        "rule_label_hi": "उच्च डायस्टोलिक BP (>90)",
    },
    {
        "code": "FREQ_URINATION",
        "name": "Frequent urination (DM screening)",
        "field_path": "survey.answers.chronic_freq_urination",
        "operator": RiskRule.Operator.TRUTHY,
        "weight": 2,
        "category": RiskRule.Category.CHRONIC,
        "rule_label_en": "Frequent urination (diabetes screening)",
        "rule_label_hi": "बार-बार पेशाब (मधुमेह जांच)",
    },
    {
        "code": "EXCESS_THIRST",
        "name": "Excessive thirst (DM screening)",
        "field_path": "survey.answers.chronic_excess_thirst",
        "operator": RiskRule.Operator.TRUTHY,
        "weight": 2,
        "category": RiskRule.Category.CHRONIC,
        "rule_label_en": "Excessive thirst (diabetes screening)",
        "rule_label_hi": "अत्यधिक प्यास (मधुमेह जांच)",
    },
    {
        "code": "CHEST_PAIN",
        "name": "Persistent chest pain",
        "field_path": "survey.answers.serious_chest_pain",
        "operator": RiskRule.Operator.TRUTHY,
        "weight": 4,
        "category": RiskRule.Category.CHRONIC,
        "rule_label_en": "Persistent chest pain",
        "rule_label_hi": "लगातार छाती दर्द",
    },
    # ── Maternal ──
    {
        "code": "PREGNANT",
        "name": "Currently pregnant",
        "field_path": "patient.metadata.pregnancy_status",
        "operator": RiskRule.Operator.TRUTHY,
        "weight": 2,
        "category": RiskRule.Category.MATERNAL,
        "rule_label_en": "Currently pregnant",
        "rule_label_hi": "गर्भवती",
    },
    {
        "code": "ANEMIA_SEVERE",
        "name": "Severe anemia (Hb < 7 g/dL)",
        "field_path": "survey.answers.hemoglobin",
        "operator": RiskRule.Operator.LT,
        "value": {"value": 7},
        "weight": 5,
        "category": RiskRule.Category.MATERNAL,
        "rule_label_en": "Severe anemia (Hb < 7 g/dL)",
        "rule_label_hi": "गंभीर एनीमिया (Hb < 7 g/dL)",
    },
    {
        "code": "ANEMIA_MODERATE",
        "name": "Moderate anemia (Hb < 11 g/dL)",
        "field_path": "survey.answers.hemoglobin",
        "operator": RiskRule.Operator.LT,
        "value": {"value": 11},
        "weight": 2,
        "category": RiskRule.Category.MATERNAL,
        "rule_label_en": "Moderate anemia (Hb < 11 g/dL)",
        "rule_label_hi": "मध्यम एनीमिया (Hb < 11 g/dL)",
    },
    {
        "code": "MISSED_ANC",
        "name": "Missed ANC visit (< 4 visits by 3rd trimester)",
        "field_path": "patient.metadata.anc_visit_count",
        "operator": RiskRule.Operator.LT,
        "value": {"value": 4},
        "weight": 3,
        "category": RiskRule.Category.MATERNAL,
        "rule_label_en": "Missed ANC visits (< 4)",
        "rule_label_hi": "ANC विजिट छूटी (< 4)",
    },
    # ── General / demographic ──
    {
        "code": "AGE_OVER_60",
        "name": "Age > 60 years",
        "field_path": "patient.age_years",
        "operator": RiskRule.Operator.GT,
        "value": {"value": 60},
        "weight": 2,
        "category": RiskRule.Category.GENERAL,
        "rule_label_en": "Age > 60 years",
        "rule_label_hi": "आयु > 60 वर्ष",
    },
    {
        "code": "AGE_UNDER_5",
        "name": "Child under 5 (IMNCI)",
        "field_path": "patient.age_years",
        "operator": RiskRule.Operator.LT,
        "value": {"value": 5},
        "weight": 2,
        "category": RiskRule.Category.GENERAL,
        "rule_label_en": "Child under 5 (IMNCI)",
        "rule_label_hi": "5 वर्ष से कम बच्चा (IMNCI)",
    },
    {
        "code": "WEAKNESS_GENERAL",
        "name": "General weakness",
        "field_path": "survey.answers.weakness",
        "operator": RiskRule.Operator.TRUTHY,
        "weight": 1,
        "category": RiskRule.Category.GENERAL,
        "rule_label_en": "General weakness",
        "rule_label_hi": "सामान्य कमज़ोरी",
    },
    {
        "code": "PERSISTENT_VOMITING",
        "name": "Persistent vomiting",
        "field_path": "survey.answers.vomiting",
        "operator": RiskRule.Operator.TRUTHY,
        "weight": 2,
        "category": RiskRule.Category.GENERAL,
        "rule_label_en": "Persistent vomiting",
        "rule_label_hi": "लगातार उल्टी",
    },
]


class Command(BaseCommand):
    help = "Seed default NHM-aligned risk rules"

    def handle(self, *args, **options):
        created = 0
        updated = 0
        for rule_data in DEFAULT_RULES:
            code = rule_data["code"]
            defaults = {k: v for k, v in rule_data.items() if k != "code"}
            _, was_created = RiskRule.objects.update_or_create(code=code, defaults=defaults)
            if was_created:
                created += 1
            else:
                updated += 1
        self.stdout.write(self.style.SUCCESS(f"Risk rules seeded: {created} created, {updated} updated"))
