"""Seed MCP-specific risk rules for maternal and child health.
Run ONCE: python manage.py seed_mcp_risk_rules
"""
import logging

from django.core.management.base import BaseCommand

from risk_engine.models import RiskRule

logger = logging.getLogger(__name__)

HARD_FLAG_RULES = [
    {
        "code": "mcp_bleeding_pregnancy",
        "name": "Bleeding during pregnancy",
        "field_path": "survey.answers.bleeding_pregnancy",
        "operator": RiskRule.Operator.TRUTHY,
        "value": {},
        "weight": 100,
        "severity": "critical",
        "flag_type": "maternal_hard_flag",
        "is_hard_flag": True,
        "category": RiskRule.Category.MATERNAL,
        "hard_flag_message_en": "EMERGENCY — bleeding during pregnancy. Hospital immediately.",
        "hard_flag_message_hi": "आपातकाल — गर्भावस्था में रक्तस्राव। तुरंत अस्पताल।",
        "rule_label_en": "Bleeding during pregnancy",
        "rule_label_hi": "गर्भावस्था में रक्तस्राव",
    },
    {
        "code": "mcp_severe_anaemia",
        "name": "Severe anaemia (Hb < 7)",
        "field_path": "anc.hemoglobin_gms",
        "operator": RiskRule.Operator.LT,
        "value": {"expected_value": 7.0},
        "weight": 100,
        "severity": "critical",
        "flag_type": "maternal_hard_flag",
        "is_hard_flag": True,
        "category": RiskRule.Category.MATERNAL,
        "hard_flag_message_en": "Severe anaemia (Hb < 7). Refer for blood transfusion.",
        "hard_flag_message_hi": "गंभीर एनीमिया (Hb < 7)। रक्त चढ़ाने भेजें।",
        "rule_label_en": "Severe anaemia (Hb < 7)",
        "rule_label_hi": "गंभीर एनीमिया (Hb < 7)",
    },
    {
        "code": "mcp_severe_pre_eclampsia",
        "name": "Severe pre-eclampsia (BP >= 160/110)",
        "field_path": "anc.bp_systolic",
        "operator": RiskRule.Operator.GTE,
        "value": {"expected_value": 160},
        "weight": 100,
        "severity": "critical",
        "flag_type": "maternal_hard_flag",
        "is_hard_flag": True,
        "category": RiskRule.Category.MATERNAL,
        "hard_flag_message_en": "Severe pre-eclampsia (BP >= 160). Call 108 immediately.",
        "hard_flag_message_hi": "गंभीर प्री-एक्लेम्पसिया (BP >= 160)। तुरंत 108 कॉल करें।",
        "rule_label_en": "Severe pre-eclampsia",
        "rule_label_hi": "गंभीर प्री-एक्लेम्पसिया",
    },
    {
        "code": "mcp_vlbw",
        "name": "Very low birth weight (< 2 kg)",
        "field_path": "patient.birth_weight_kg",
        "operator": RiskRule.Operator.LT,
        "value": {"expected_value": 2.0},
        "weight": 100,
        "severity": "critical",
        "flag_type": "child_hard_flag",
        "is_hard_flag": True,
        "category": RiskRule.Category.CHILD,
        "hard_flag_message_en": "Birth weight < 2 kg. Needs Kangaroo Mother Care. Refer to SNCU.",
        "hard_flag_message_hi": "जन्म वजन 2 kg से कम। SNCU भेजें।",
        "rule_label_en": "Very low birth weight (< 2 kg)",
        "rule_label_hi": "बहुत कम जन्म वजन (< 2 kg)",
    },
    {
        "code": "mcp_newborn_convulsions",
        "name": "Newborn convulsions",
        "field_path": "pnc.baby_convulsions",
        "operator": RiskRule.Operator.TRUTHY,
        "value": {},
        "weight": 100,
        "severity": "critical",
        "flag_type": "critical_hard_flag",
        "is_hard_flag": True,
        "category": RiskRule.Category.CRITICAL,
        "hard_flag_message_en": "Newborn convulsions. Emergency — call 108.",
        "hard_flag_message_hi": "नवजात को दौरे। आपातकाल — 108 कॉल करें।",
        "rule_label_en": "Newborn convulsions",
        "rule_label_hi": "नवजात को दौरे",
    },
    {
        "code": "mcp_sam",
        "name": "Severe acute malnutrition (below -3SD)",
        "field_path": "growth.nutritional_status",
        "operator": RiskRule.Operator.EQ,
        "value": {"expected_value": "severe_underweight"},
        "weight": 100,
        "severity": "critical",
        "flag_type": "child_hard_flag",
        "is_hard_flag": True,
        "category": RiskRule.Category.CHILD,
        "hard_flag_message_en": "Severe acute malnutrition. Refer to NRC immediately.",
        "hard_flag_message_hi": "गंभीर कुपोषण। NRC तुरंत भेजें।",
        "rule_label_en": "Severe acute malnutrition (below -3SD)",
        "rule_label_hi": "गंभीर कुपोषण (-3SD से नीचे)",
    },
    {
        "code": "mcp_dev_warning_sign",
        "name": "Development warning sign",
        "field_path": "milestone.any_warning_sign",
        "operator": RiskRule.Operator.TRUTHY,
        "value": {},
        "weight": 100,
        "severity": "critical",
        "flag_type": "child_hard_flag",
        "is_hard_flag": True,
        "category": RiskRule.Category.CHILD,
        "hard_flag_message_en": "Developmental warning sign. Refer to developmental clinic.",
        "hard_flag_message_hi": "विकास में रुकावट। विकास क्लिनिक भेजें।",
        "rule_label_en": "Developmental warning sign",
        "rule_label_hi": "विकास में रुकावट",
    },
]

SCORING_RULES = [
    # Maternal scoring rules
    {
        "code": "mcp_low_anc_visits",
        "name": "Low ANC visit count (< 4)",
        "field_path": "patient.anc_visit_count",
        "operator": RiskRule.Operator.LT,
        "value": {"expected_value": 4},
        "weight": 3,
        "severity": "medium",
        "flag_type": "maternal_risk",
        "category": RiskRule.Category.MATERNAL,
        "rule_label_en": "Low ANC visits (< 4 completed)",
        "rule_label_hi": "कम ANC विज़िट (4 से कम)",
    },
    {
        "code": "mcp_low_hemoglobin",
        "name": "Low haemoglobin (< 10 g/dL)",
        "field_path": "anc.hemoglobin_gms",
        "operator": RiskRule.Operator.LT,
        "value": {"expected_value": 10.0},
        "weight": 3,
        "severity": "medium",
        "flag_type": "maternal_risk",
        "category": RiskRule.Category.MATERNAL,
        "rule_label_en": "Low haemoglobin (Hb < 10 g/dL)",
        "rule_label_hi": "कम हीमोग्लोबिन (Hb < 10)",
    },
    {
        "code": "mcp_moderate_anaemia",
        "name": "Moderate anaemia (Hb 7-10)",
        "field_path": "anc.hemoglobin_gms",
        "operator": RiskRule.Operator.LT,
        "value": {"expected_value": 11.0},
        "weight": 2,
        "severity": "medium",
        "flag_type": "maternal_risk",
        "category": RiskRule.Category.MATERNAL,
        "rule_label_en": "Moderate anaemia (Hb 7-10 g/dL)",
        "rule_label_hi": "मध्यम एनीमिया (Hb 7-10)",
    },
    {
        "code": "mcp_high_bp",
        "name": "High BP (systolic >= 140)",
        "field_path": "anc.bp_systolic",
        "operator": RiskRule.Operator.GTE,
        "value": {"expected_value": 140},
        "weight": 3,
        "severity": "high",
        "flag_type": "maternal_risk",
        "category": RiskRule.Category.MATERNAL,
        "rule_label_en": "High blood pressure (BP >= 140 systolic)",
        "rule_label_hi": "उच्च रक्तचाप (BP >= 140)",
    },
    {
        "code": "mcp_proteinuria",
        "name": "Urine albumin positive (>= +1)",
        "field_path": "anc.urine_albumin",
        "operator": RiskRule.Operator.GTE,
        "value": {"expected_value": 1},
        "weight": 3,
        "severity": "high",
        "flag_type": "maternal_risk",
        "category": RiskRule.Category.MATERNAL,
        "rule_label_en": "Urine albumin positive (pre-eclampsia risk)",
        "rule_label_hi": "मूत्र में एल्ब्युमिन (प्री-एक्लेम्पसिया जोखिम)",
    },
    {
        "code": "mcp_high_bmi",
        "name": "High BMI (>= 30)",
        "field_path": "anc.bmi",
        "operator": RiskRule.Operator.GTE,
        "value": {"expected_value": 30},
        "weight": 2,
        "severity": "medium",
        "flag_type": "maternal_risk",
        "category": RiskRule.Category.MATERNAL,
        "rule_label_en": "High BMI (>= 30)",
        "rule_label_hi": "उच्च BMI (>= 30)",
    },
    {
        "code": "mcp_maternal_age_risk",
        "name": "Maternal age < 18 or > 35",
        "field_path": "patient.age_years",
        "operator": RiskRule.Operator.LT,
        "value": {"expected_value": 18},
        "weight": 2,
        "severity": "medium",
        "flag_type": "maternal_risk",
        "category": RiskRule.Category.MATERNAL,
        "rule_label_en": "Maternal age < 18 or > 35 (young or advanced age)",
        "rule_label_hi": "मातृ आयु < 18 या > 35 (कम या अधिक आयु)",
    },
    {
        "code": "mcp_maternal_age_risk_high",
        "name": "Maternal age > 35",
        "field_path": "patient.age_years",
        "operator": RiskRule.Operator.GT,
        "value": {"expected_value": 35},
        "weight": 3,
        "severity": "high",
        "flag_type": "maternal_risk",
        "category": RiskRule.Category.MATERNAL,
        "rule_label_en": "Maternal age > 35",
        "rule_label_hi": "मातृ आयु > 35",
    },
    {
        "code": "mcp_high_parity",
        "name": "High parity (>= 4)",
        "field_path": "patient.gravida",
        "operator": RiskRule.Operator.GTE,
        "value": {"expected_value": 4},
        "weight": 2,
        "severity": "medium",
        "flag_type": "maternal_risk",
        "category": RiskRule.Category.MATERNAL,
        "rule_label_en": "High parity (>= 4 previous births)",
        "rule_label_hi": "अधिक प्रसव (4 या अधिक पिछले जन्म)",
    },
    {
        "code": "mcp_previous_cs",
        "name": "Previous C-section",
        "field_path": "survey.answers.previous_cs",
        "operator": RiskRule.Operator.TRUTHY,
        "value": {},
        "weight": 3,
        "severity": "high",
        "flag_type": "maternal_risk",
        "category": RiskRule.Category.MATERNAL,
        "rule_label_en": "Previous C-section delivery",
        "rule_label_hi": "पिछला सिजेरियन प्रसव",
    },
    {
        "code": "mcp_post_term",
        "name": "Post-term pregnancy (> 40 weeks POG)",
        "field_path": "anc.pog_weeks",
        "operator": RiskRule.Operator.GT,
        "value": {"expected_value": 40},
        "weight": 2,
        "severity": "medium",
        "flag_type": "maternal_risk",
        "category": RiskRule.Category.MATERNAL,
        "rule_label_en": "Post-term pregnancy (> 40 weeks POG)",
        "rule_label_hi": "गर्भावस्था 40 सप्ताह से अधिक",
    },
    {
        "code": "mcp_no_delivery_plan",
        "name": "No delivery plan",
        "field_path": "survey.answers.delivery_plan",
        "operator": RiskRule.Operator.FALSY,
        "value": {},
        "weight": 1,
        "severity": "low",
        "flag_type": "maternal_risk",
        "category": RiskRule.Category.MATERNAL,
        "rule_label_en": "No delivery plan prepared",
        "rule_label_hi": "प्रसव योजना तैयार नहीं",
    },
    # Child scoring rules
    {
        "code": "mcp_underweight",
        "name": "Underweight (WFA Z-score < -2 SD)",
        "field_path": "growth.wfa_z_score",
        "operator": RiskRule.Operator.LT,
        "value": {"expected_value": -2.0},
        "weight": 2,
        "severity": "medium",
        "flag_type": "child_risk",
        "category": RiskRule.Category.CHILD,
        "rule_label_en": "Underweight (WFA Z-score < -2 SD)",
        "rule_label_hi": "कम वजन (WFA Z-score < -2 SD)",
    },
    {
        "code": "mcp_missed_vaccines",
        "name": "Missed vaccines (> 0)",
        "field_path": "patient.missed_vaccine_count",
        "operator": RiskRule.Operator.GT,
        "value": {"expected_value": 0},
        "weight": 2,
        "severity": "medium",
        "flag_type": "child_risk",
        "category": RiskRule.Category.CHILD,
        "rule_label_en": "Missed vaccinations",
        "rule_label_hi": "छूटे हुए टीके",
    },
    {
        "code": "mcp_weight_faltering",
        "name": "Weight faltering (not gaining)",
        "field_path": "growth.is_faltering",
        "operator": RiskRule.Operator.TRUTHY,
        "value": {},
        "weight": 2,
        "severity": "medium",
        "flag_type": "child_risk",
        "category": RiskRule.Category.CHILD,
        "rule_label_en": "Weight faltering (not gaining weight)",
        "rule_label_hi": "वजन नहीं बढ़ रहा",
    },
    {
        "code": "mcp_low_muac",
        "name": "Low MUAC (< 12.5 cm)",
        "field_path": "growth.muac_cm",
        "operator": RiskRule.Operator.LT,
        "value": {"expected_value": 12.5},
        "weight": 2,
        "severity": "medium",
        "flag_type": "child_risk",
        "category": RiskRule.Category.CHILD,
        "rule_label_en": "Low MUAC (< 12.5 cm)",
        "rule_label_hi": "कम MUAC (< 12.5 cm)",
    },
    {
        "code": "mcp_low_birth_weight_score",
        "name": "Low birth weight (< 2.5 kg)",
        "field_path": "patient.birth_weight_kg",
        "operator": RiskRule.Operator.LT,
        "value": {"expected_value": 2.5},
        "weight": 2,
        "severity": "medium",
        "flag_type": "child_risk",
        "category": RiskRule.Category.CHILD,
        "rule_label_en": "Low birth weight (< 2.5 kg)",
        "rule_label_hi": "कम जन्म वजन (< 2.5 kg)",
    },
    {
        "code": "mcp_stunted",
        "name": "Stunted (HFA Z-score < -2 SD)",
        "field_path": "growth.hfa_z_score",
        "operator": RiskRule.Operator.LT,
        "value": {"expected_value": -2.0},
        "weight": 2,
        "severity": "medium",
        "flag_type": "child_risk",
        "category": RiskRule.Category.CHILD,
        "rule_label_en": "Stunted (HFA Z-score < -2 SD)",
        "rule_label_hi": "बौनापन (HFA Z-score < -2 SD)",
    },
    {
        "code": "mcp_no_exclusive_bf",
        "name": "Not exclusively breastfed (0-6 months)",
        "field_path": "survey.answers.exclusive_breastfeeding",
        "operator": RiskRule.Operator.FALSY,
        "value": {},
        "weight": 1,
        "severity": "low",
        "flag_type": "child_risk",
        "category": RiskRule.Category.CHILD,
        "rule_label_en": "Not exclusively breastfed (0-6 months)",
        "rule_label_hi": "विशेष स्तनपान नहीं (0-6 माह)",
    },
]

RULES = HARD_FLAG_RULES + SCORING_RULES


class Command(BaseCommand):
    help = "Seed MCP maternal/child risk rules into the risk_rules table"

    def handle(self, *args, **options):
        created = 0
        skipped = 0
        for data in RULES:
            _, was_created = RiskRule.objects.get_or_create(
                code=data["code"],
                defaults=data,
            )
            if was_created:
                created += 1
            else:
                skipped += 1
        self.stdout.write(self.style.SUCCESS(f"MCP risk rules: {created} created, {skipped} skipped"))
