# Generated by Django 5.2.14 on 2026-06-02 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("followups", "0012_uber_architecture"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="H3Cell",
            fields=[
                (
                    "cell_id",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("resolution", models.PositiveSmallIntegerField(default=8)),
                ("center_lat", models.FloatField()),
                ("center_lng", models.FloatField()),
                (
                    "district",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                (
                    "block",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                ("worker_count", models.PositiveIntegerField(default=0)),
                ("household_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "H3 Cell",
                "verbose_name_plural": "H3 Cells",
                "ordering": ["cell_id"],
            },
        ),
        migrations.CreateModel(
            name="LocationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("accuracy_m", models.FloatField(blank=True, null=True)),
                ("altitude_m", models.FloatField(blank=True, null=True)),
                ("speed_mps", models.FloatField(blank=True, null=True)),
                (
                    "battery_pct",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "h3_cell_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=16
                    ),
                ),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("is_during_visit", models.BooleanField(default=False)),
                (
                    "visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="location_logs",
                        to="followups.followup",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["worker", "-recorded_at"], name="idx_loc_worker_time"
                    ),
                    models.Index(
                        fields=["h3_cell_id", "-recorded_at"], name="idx_loc_h3_time"
                    ),
                ],
            },
        ),
    ]
