from io import BytesIO

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table


class PayslipService:
    def generate(self, worker, incentives, month_year, supervisor=None):
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=30, bottomMargin=30)
        story = []
        styles = getSampleStyleSheet()

        story.append(Paragraph(
            "<b>GOVERNMENT OF INDIA — MINISTRY OF HEALTH AND FAMILY WELFARE</b>",
            styles["Heading2"],
        ))
        story.append(Paragraph(
            "National Health Mission — ASHA Incentive Payslip",
            styles["Normal"],
        ))
        story.append(Spacer(1, 12))

        worker_data = [
            ["ASHA Name", worker.get_full_name() or worker.phone or "—", "नाम", "—"],
            ["Worker ID", str(worker.pk), "कर्मचारी ID", str(worker.pk)],
            ["Village", worker.village or "—", "ग्राम", worker.village or "—"],
            ["Block", worker.block or "—", "ब्लॉक", worker.block or "—"],
            ["Month", month_year, "माह", month_year],
        ]
        story.append(Table(worker_data, colWidths=[120, 160, 100, 120]))
        story.append(Spacer(1, 16))

        headers = ["Activity", "Date", "Status", "Amount (₹)"]
        rows = [headers]
        total_paid = 0
        for inc in incentives:
            amount = inc.amount_paise // 100
            rows.append([
                inc.description_en or inc.activity_type.replace("_", " ").title(),
                inc.created_at.strftime("%d %b %Y") if inc.created_at else "—",
                inc.status.upper(),
                f"₹{amount}",
            ])
            if inc.status == "paid":
                total_paid += amount

        rows.append(["", "", "TOTAL PAID", f"₹{total_paid}"])
        story.append(Table(rows, colWidths=[220, 80, 80, 80]))
        story.append(Spacer(1, 20))

        story.append(Paragraph("ASHA Worker Signature: _____________", styles["Normal"]))
        story.append(Paragraph("ANM Supervisor Signature: _____________", styles["Normal"]))
        story.append(Spacer(1, 8))
        story.append(Paragraph(
            "Generated by Saasthi Digital Platform · Ministry of Health & Family Welfare, GOI",
            styles["Normal"],
        ))

        doc.build(story)
        return buffer.getvalue()
