# Generated by Django 5.2.14 on 2026-05-21 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mcp", "0001_initial"),
        ("registry", "0003_alter_household_block_alter_household_district_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="careinteraction",
            index=models.Index(fields=["patient", "protocol"], name="ix_ci_patient_protocol"),
        ),
        migrations.AddIndex(
            model_name="careinteraction",
            index=models.Index(fields=["occurred_at"], name="ix_ci_occurred_at"),
        ),
    ]
