# Generated by Django 5.2.14 on 2026-05-23 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mcp", "0003_deliveryrecord_developmentmilestonecheck_and_more"),
        ("registry", "0006_add_missing_db_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ancvisit",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="anc_visits",
                to="registry.patient",
            ),
        ),
        migrations.AlterField(
            model_name="careinteraction",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="care_interactions",
                to="registry.patient",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryrecord",
            name="mother_patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliveries",
                to="registry.patient",
            ),
        ),
        migrations.AlterField(
            model_name="developmentmilestonecheck",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="milestone_checks",
                to="registry.patient",
            ),
        ),
        migrations.AlterField(
            model_name="growthrecord",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="growth_records",
                to="registry.patient",
            ),
        ),
        migrations.AlterField(
            model_name="ifacompliance",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ifa_compliance",
                to="registry.patient",
            ),
        ),
        migrations.AlterField(
            model_name="immunizationrecord",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="immunizations",
                to="registry.patient",
            ),
        ),
        migrations.AlterField(
            model_name="mcpsurveysession",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mcp_sessions",
                to="registry.patient",
            ),
        ),
        migrations.AlterField(
            model_name="pncvisit",
            name="mother_patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pnc_visits",
                to="registry.patient",
            ),
        ),
    ]
