# Generated by Django 5.2.14 on 2026-05-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcp", "0004_alter_ancvisit_patient_alter_careinteraction_patient_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mcpsurveysession",
            options={"ordering": ["-session_date", "-created_at"]},
        ),
        migrations.AlterField(
            model_name="deliveryrecord",
            name="delivery_outcome",
            field=models.CharField(
                choices=[
                    ("live_birth", "Live Birth"),
                    ("still_birth", "Still Birth"),
                    ("abortion", "Abortion"),
                    ("missed_abortion", "Missed Abortion"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="deliveryrecord",
            name="delivery_place",
            field=models.CharField(
                choices=[
                    ("home", "Home"),
                    ("institution", "Institution"),
                    ("en_route", "En Route"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="deliveryrecord",
            name="delivery_type",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("cs", "C-Section"),
                    ("instrumental", "Instrumental"),
                    ("other", "Other"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="mcpsurveysession",
            name="session_type",
            field=models.CharField(
                choices=[
                    ("anc_visit", "ANC Visit"),
                    ("delivery_record", "Delivery Record"),
                    ("pnc_visit", "PNC Visit"),
                    ("child_growth", "Child Growth"),
                    ("immunization_update", "Immunization Update"),
                    ("milestone_check", "Milestone Check"),
                    ("care_interaction", "Care Interaction"),
                    ("general_survey", "General Survey"),
                    ("registration", "MCP Registration"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="pncvisit",
            name="visit_timing",
            field=models.CharField(
                choices=[
                    ("24hrs", "Within 24 hours"),
                    ("day3", "Day 3"),
                    ("day7", "Day 7"),
                    ("day14", "Day 14"),
                    ("day21", "Day 21"),
                    ("day28", "Day 28"),
                    ("extra", "Extra Visit"),
                ],
                max_length=10,
            ),
        ),
    ]
