# Generated by Codex on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mcp", "0005_alter_mcpsurveysession_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pncvisit",
            name="visit_timing",
            field=models.CharField(
                choices=[
                    ("24hrs", "Within 24 hours"),
                    ("day3", "Day 3"),
                    ("day7", "Day 7"),
                    ("day14", "Day 14"),
                    ("day21", "Day 21"),
                    ("day28", "Day 28"),
                    ("day42", "Day 42"),
                    ("extra", "Extra Visit"),
                ],
                max_length=10,
            ),
        ),
    ]
