# Generated by Django 5.2.14 on 2026-05-21 21:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcp", "0002_careinteraction_ix_ci_patient_protocol_and_more"),
        ("registry", "0003_alter_household_block_alter_household_district_and_more"),
        ("risk_engine", "0005_riskassessment_mcp_session_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "local_uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("delivery_date", models.DateField()),
                ("delivery_place", models.CharField(max_length=20)),
                (
                    "institution_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("delivery_type", models.CharField(max_length=10)),
                ("delivery_outcome", models.CharField(max_length=15)),
                ("baby_sex", models.CharField(blank=True, max_length=10, null=True)),
                ("birth_weight_kg", models.FloatField(blank=True, null=True)),
                ("birth_weight_grams", models.IntegerField(blank=True, null=True)),
                ("baby_cried_immediately", models.BooleanField(blank=True, null=True)),
                ("breastfeed_within_1hr", models.BooleanField(blank=True, null=True)),
                ("vitamin_k_given", models.BooleanField(blank=True, null=True)),
                ("complications", models.TextField(blank=True)),
                ("ifa_postnatal_started", models.BooleanField(default=False)),
                ("calcium_postnatal_started", models.BooleanField(default=False)),
                ("institution_stay_days", models.IntegerField(blank=True, null=True)),
                ("jsy_registered", models.BooleanField(default=False)),
                ("pmmvy_registered", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asha_worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "child_patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="birth_record",
                        to="registry.patient",
                    ),
                ),
                (
                    "mother_patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="registry.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DevelopmentMilestoneCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "local_uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("check_date", models.DateField()),
                ("age_at_check_months", models.IntegerField()),
                ("milestones_achieved", models.JSONField(blank=True, default=dict)),
                ("warning_signs", models.JSONField(blank=True, default=dict)),
                ("any_warning_sign", models.BooleanField(default=False)),
                ("developmental_concern", models.TextField(blank=True)),
                (
                    "referred_to",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asha_worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestone_checks",
                        to="registry.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GrowthRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "local_uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("recorded_date", models.DateField()),
                ("recorded_by", models.CharField(max_length=10)),
                ("age_completed_months", models.FloatField()),
                ("weight_kg", models.FloatField()),
                ("height_cm", models.FloatField(blank=True, null=True)),
                ("muac_cm", models.FloatField(blank=True, null=True)),
                ("wfa_z_score", models.FloatField(blank=True, null=True)),
                ("wfh_z_score", models.FloatField(blank=True, null=True)),
                ("hfa_z_score", models.FloatField(blank=True, null=True)),
                ("nutritional_status", models.CharField(max_length=20)),
                ("weight_change_kg", models.FloatField(blank=True, null=True)),
                ("is_faltering", models.BooleanField(default=False)),
                ("aww_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asha_worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="growth_records",
                        to="registry.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IFACompliance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "local_uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("record_date", models.DateField()),
                ("year_month", models.CharField(max_length=7)),
                ("week_number", models.IntegerField()),
                ("dose_given", models.BooleanField(default=False)),
                ("dose_day", models.CharField(blank=True, max_length=10, null=True)),
                ("bottle_number", models.IntegerField(blank=True, null=True)),
                ("albendazole_given", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asha_worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ifa_compliance",
                        to="registry.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImmunizationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "local_uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "vaccine_name",
                    models.CharField(
                        choices=[
                            ("BCG", "BCG"),
                            ("OPV0", "OPV-0"),
                            ("HepB", "Hep-B"),
                            ("OPV1", "OPV-1"),
                            ("Penta1", "Penta-1"),
                            ("Rota1", "Rota-1"),
                            ("PCV1", "PCV-1"),
                            ("IPV1", "IPV-1"),
                            ("OPV2", "OPV-2"),
                            ("Penta2", "Penta-2"),
                            ("Rota2", "Rota-2"),
                            ("OPV3", "OPV-3"),
                            ("Penta3", "Penta-3"),
                            ("Rota3", "Rota-3"),
                            ("PCV2", "PCV-2"),
                            ("IPV2", "IPV-2"),
                            ("MR1", "MR-1"),
                            ("JE1", "JE-1"),
                            ("VitA1", "Vitamin-A-1"),
                            ("PCVBooster", "PCV-Booster"),
                            ("MR2", "MR-2"),
                            ("JE2", "JE-2"),
                            ("DPTBooster1", "DPT-Booster-1"),
                            ("OPVBooster", "OPV-Booster"),
                            ("VitA2", "Vitamin-A-2"),
                            ("VitA3-9", "Vitamin-A-3-9"),
                            ("DPTBooster2", "DPT-Booster-2"),
                            ("TT10yr", "TT-10yr"),
                            ("TT16yr", "TT-16yr"),
                        ],
                        max_length=20,
                    ),
                ),
                ("dose_number", models.IntegerField(default=1)),
                ("scheduled_date", models.DateField()),
                ("administered_date", models.DateField(blank=True, null=True)),
                (
                    "administered_at",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("due", "Due"),
                            ("given", "Given"),
                            ("missed", "Missed"),
                            ("overdue", "Overdue"),
                        ],
                        default="due",
                        max_length=10,
                    ),
                ),
                ("missed_reason", models.TextField(blank=True)),
                ("next_reschedule", models.DateField(blank=True, null=True)),
                ("fic_eligible", models.BooleanField(default=False)),
                ("cic_eligible", models.BooleanField(default=False)),
                ("is_vitamin_a", models.BooleanField(default=False)),
                ("vitamin_a_dose_num", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asha_worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="immunizations",
                        to="registry.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MCPSurveySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "local_uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("session_date", models.DateField()),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("anc_visit", "ANC Visit"),
                            ("delivery_record", "Delivery Record"),
                            ("pnc_visit", "PNC Visit"),
                            ("child_growth", "Child Growth"),
                            ("immunization_update", "Immunization Update"),
                            ("milestone_check", "Milestone Check"),
                            ("general_survey", "General Survey"),
                            ("registration", "MCP Registration"),
                        ],
                        max_length=30,
                    ),
                ),
                ("linked_record_id", models.UUIDField(blank=True, null=True)),
                (
                    "linked_record_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asha_worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_sessions",
                        to="registry.patient",
                    ),
                ),
                (
                    "risk_assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="risk_engine.riskassessment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PNCVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "local_uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("visit_timing", models.CharField(max_length=10)),
                ("visit_date", models.DateField()),
                ("mother_complaints", models.TextField(blank=True)),
                (
                    "mother_pallor",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("mother_pulse", models.IntegerField(blank=True, null=True)),
                ("mother_bp_sys", models.IntegerField(blank=True, null=True)),
                ("mother_bp_dia", models.IntegerField(blank=True, null=True)),
                ("mother_temp_f", models.FloatField(blank=True, null=True)),
                (
                    "breasts_condition",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "nipples_condition",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "uterus_tenderness",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("bleeding_pv", models.CharField(blank=True, max_length=10, null=True)),
                ("lochia", models.CharField(blank=True, max_length=15, null=True)),
                ("episiotomy", models.CharField(blank=True, max_length=10, null=True)),
                ("family_planning_counselled", models.BooleanField(default=False)),
                ("baby_weight_kg", models.FloatField(blank=True, null=True)),
                ("baby_urine", models.BooleanField(blank=True, null=True)),
                ("baby_stool", models.BooleanField(blank=True, null=True)),
                ("baby_diarrhoea", models.BooleanField(default=False)),
                ("baby_vomiting", models.BooleanField(default=False)),
                ("baby_convulsions", models.BooleanField(default=False)),
                (
                    "baby_activity",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "baby_sucking",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "baby_breathing",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("baby_chest_indrawing", models.BooleanField(default=False)),
                ("baby_temp_f", models.FloatField(blank=True, null=True)),
                ("baby_jaundice", models.BooleanField(default=False)),
                (
                    "umbilical_stump",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("is_extra_visit", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asha_worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delivery_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mcp.deliveryrecord",
                    ),
                ),
                (
                    "mother_patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pnc_visits",
                        to="registry.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WHOGrowthReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sex", models.CharField(max_length=6)),
                ("age_months", models.FloatField()),
                ("measurement_type", models.CharField(max_length=10)),
                ("sd_minus_3", models.FloatField()),
                ("sd_minus_2", models.FloatField()),
                ("sd_minus_1", models.FloatField()),
                ("median", models.FloatField()),
                ("sd_plus_1", models.FloatField()),
                ("sd_plus_2", models.FloatField()),
                ("sd_plus_3", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["sex", "age_months", "measurement_type"],
                        name="ix_who_growth_ref",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sex", "age_months", "measurement_type"),
                        name="uq_who_growth_ref",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ANCVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "local_uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("visit_number", models.IntegerField()),
                ("visit_date", models.DateField()),
                ("pog_weeks", models.IntegerField(blank=True, null=True)),
                ("weight_kg", models.FloatField(blank=True, null=True)),
                ("pulse_rate", models.IntegerField(blank=True, null=True)),
                ("bp_systolic", models.IntegerField(blank=True, null=True)),
                ("bp_diastolic", models.IntegerField(blank=True, null=True)),
                ("pallor", models.CharField(blank=True, max_length=10, null=True)),
                ("oedema", models.CharField(blank=True, max_length=10, null=True)),
                ("jaundice", models.CharField(blank=True, max_length=10, null=True)),
                ("any_complaints", models.TextField(blank=True)),
                ("fundal_height_cm", models.FloatField(blank=True, null=True)),
                (
                    "lie_presentation",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "fetal_movements",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("fetal_heart_rate", models.IntegerField(blank=True, null=True)),
                ("pv_done", models.BooleanField(default=False)),
                ("hemoglobin_gms", models.FloatField(blank=True, null=True)),
                (
                    "urine_albumin",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("urine_sugar", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "hiv_screening",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "syphilis_test",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("ultrasonography", models.BooleanField(blank=True, null=True)),
                (
                    "gdm_screening",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("blood_group", models.CharField(blank=True, max_length=5, null=True)),
                ("rh_typing", models.CharField(blank=True, max_length=3, null=True)),
                ("tsh_value", models.FloatField(blank=True, null=True)),
                ("hbsag", models.CharField(blank=True, max_length=10, null=True)),
                ("blood_sugar_value", models.FloatField(blank=True, null=True)),
                ("tt_injection_given", models.BooleanField(default=False)),
                ("ifa_tablets_given", models.IntegerField(default=0)),
                ("calcium_tablets_given", models.BooleanField(default=False)),
                ("albendazole_given", models.BooleanField(default=False)),
                ("is_high_risk", models.BooleanField(default=False)),
                ("risk_flags_summary", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asha_worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anc_visits",
                        to="registry.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["patient", "visit_number"],
                "indexes": [
                    models.Index(
                        fields=["patient", "visit_number"], name="ix_anc_patient_visit"
                    ),
                    models.Index(
                        fields=["patient", "visit_date"], name="ix_anc_patient_date"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="deliveryrecord",
            index=models.Index(fields=["mother_patient"], name="ix_delivery_mother"),
        ),
        migrations.AddIndex(
            model_name="deliveryrecord",
            index=models.Index(fields=["delivery_date"], name="ix_delivery_date"),
        ),
        migrations.AddIndex(
            model_name="deliveryrecord",
            index=models.Index(fields=["child_patient"], name="ix_delivery_child"),
        ),
        migrations.AddIndex(
            model_name="developmentmilestonecheck",
            index=models.Index(
                fields=["patient", "age_at_check_months"],
                name="ix_milestone_patient_age",
            ),
        ),
        migrations.AddIndex(
            model_name="developmentmilestonecheck",
            index=models.Index(
                fields=["any_warning_sign"], name="ix_milestone_warning"
            ),
        ),
        migrations.AddIndex(
            model_name="growthrecord",
            index=models.Index(
                fields=["patient", "recorded_date"], name="ix_growth_patient_date"
            ),
        ),
        migrations.AddIndex(
            model_name="growthrecord",
            index=models.Index(
                fields=["nutritional_status"], name="ix_growth_nutrition"
            ),
        ),
        migrations.AddIndex(
            model_name="ifacompliance",
            index=models.Index(
                fields=["patient", "year_month"], name="ix_ifa_patient_month"
            ),
        ),
        migrations.AddIndex(
            model_name="immunizationrecord",
            index=models.Index(
                fields=["patient", "status"], name="ix_immunization_patient_status"
            ),
        ),
        migrations.AddIndex(
            model_name="immunizationrecord",
            index=models.Index(
                fields=["scheduled_date", "status"], name="ix_immu_sched_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="immunizationrecord",
            constraint=models.UniqueConstraint(
                fields=("patient", "vaccine_name", "dose_number"),
                name="uq_immunization_patient_vaccine_dose",
            ),
        ),
        migrations.AddIndex(
            model_name="mcpsurveysession",
            index=models.Index(
                fields=["patient", "session_date"], name="ix_mcp_session_patient_date"
            ),
        ),
        migrations.AddIndex(
            model_name="mcpsurveysession",
            index=models.Index(fields=["session_type"], name="ix_mcp_session_type"),
        ),
        migrations.AddIndex(
            model_name="pncvisit",
            index=models.Index(
                fields=["mother_patient", "visit_timing"], name="ix_pnc_mother_timing"
            ),
        ),
        migrations.AddIndex(
            model_name="pncvisit",
            index=models.Index(fields=["delivery_record"], name="ix_pnc_delivery"),
        ),
    ]
