# Generated by Django 5.2.14 on 2026-05-21 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="household",
            name="head_name",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="household",
            name="head_name_hi",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="household",
            name="household_code",
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="household",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="household",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="household",
            name="lng",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="household",
            name="member_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="patient",
            name="asha_worker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_patients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="diabetes",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patient",
            name="hypertension",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patient",
            name="name_hi",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="patient",
            name="pregnancy_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patient",
            name="prev_high_risk_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="patient",
            name="prev_hospitalized",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patient",
            name="relationship_to_head",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="patient",
            name="tb_history",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="patient",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_patients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="household",
            index=models.Index(fields=["village", "is_active"], name="ix_household_village_active"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["household"], name="ix_patient_household"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["asha_worker"], name="ix_patient_asha_worker"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["status"], name="ix_patient_status"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["village", "status"], name="ix_patient_village_status"),
        ),
    ]
