# Generated by Django 5.2.14 on 2026-05-21 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0003_alter_household_block_alter_household_district_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="anc_visit_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="patient",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="bank_branch_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="bank_ifsc",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="birth_place",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="birth_registration_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="birth_weight_kg",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="edd",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="gravida",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="is_high_risk_pregnancy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patient",
            name="last_delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="last_delivery_place",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="lmp_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="mcp_card_issued",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patient",
            name="mcp_card_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="mcts_rch_id",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="mother_patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="registry.patient",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="obstetric_complications",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="patient",
            name="para",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="past_medical_history",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="patient",
            name="pmmvy_eligible",
            field=models.BooleanField(default=False),
        ),
    ]
