# Generated by Django 5.2.14 on 2026-05-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "registry",
            "0004_patient_anc_visit_count_patient_bank_account_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="abha_consent_given",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patient",
            name="abha_number",
            field=models.CharField(
                blank=True,
                help_text="ABHA Health ID",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="fhir_bundle",
            field=models.JSONField(
                blank=True, default=dict, help_text="Cached FHIR Patient bundle"
            ),
        ),
    ]
