# Generated by Django 5.2.14 on 2026-05-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0005_add_abdm_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[
                    ("female", "Female"),
                    ("male", "Male"),
                    ("other", "Other"),
                    ("unknown", "Unknown"),
                ],
                db_index=True,
                default="unknown",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="patient",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
