# Generated by Django 5.2.14 on 2026-05-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0006_add_missing_db_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="abortions",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="blood_group",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="mcp_registration_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="rh_typing",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
