# Generated by Django 5.2.14 on 2026-05-19 05:17

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("registry", "0001_initial"),
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                (
                    "field_path",
                    models.CharField(
                        help_text="patient.age_years or survey.answers.key",
                        max_length=180,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("eq", "Equals"),
                            ("gte", "Greater than or equal"),
                            ("lte", "Less than or equal"),
                            ("contains", "Contains"),
                            ("truthy", "Truthy"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.JSONField(blank=True, default=dict)),
                ("weight", models.PositiveIntegerField(default=1)),
                ("severity", models.CharField(default="medium", max_length=20)),
                ("flag_type", models.CharField(default="clinical_risk", max_length=80)),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RiskAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "local_uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("total_score", models.PositiveIntegerField(default=0)),
                ("level", models.CharField(default="low", max_length=20)),
                ("explanations", models.JSONField(blank=True, default=list)),
                ("rules_version", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_assessments",
                        to="registry.patient",
                    ),
                ),
                (
                    "survey_response",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="surveys.surveyresponse",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
