# Generated by Django 5.2.14 on 2026-05-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk_engine", "0002_risk_engine_v2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskassessment",
            name="rules_snapshot",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="MLModelVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(unique=True)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("file_size_bytes", models.PositiveIntegerField(blank=True, null=True)),
                ("cv_f1_macro", models.FloatField(blank=True, null=True)),
                (
                    "n_training_samples",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("schema_version", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=False)),
                ("trained_at", models.DateTimeField(blank=True, null=True)),
                ("deployed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-version"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="uq_ml_model_active",
                    )
                ],
            },
        ),
    ]
