# Generated by Django 5.2.14 on 2026-05-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk_engine", "0003_alter_riskassessment_rules_snapshot_mlmodelversion"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskassessment",
            name="ml_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="riskassessment",
            name="ml_model_version",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="riskassessment",
            name="ml_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="riskassessment",
            name="recommendation_source",
            field=models.CharField(
                blank=True,
                default="rule_template",
                help_text="rule_template | gemma4_api | tflite",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="riskassessment",
            name="rule_engine_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="riskassessment",
            name="score_source",
            field=models.CharField(
                blank=True,
                default="rule_engine",
                help_text="rule_engine | tflite | ml_ensemble",
                max_length=30,
            ),
        ),
    ]
