# Generated by Django 5.2.14 on 2026-05-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("risk_engine", "0004_risk_assessment_source_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskassessment",
            name="mcp_session_type",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="riskassessment",
            name="patient_population",
            field=models.CharField(
                blank=True,
                default="general",
                help_text="general|maternal|child",
                max_length=10,
            ),
        ),
    ]
