# Generated by Django 5.2.14 on 2026-05-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk_engine", "0006_alter_riskassessment_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskassessment",
            name="feature_vector",
            field=models.JSONField(
                blank=True,
                help_text="MCP feature extractor output (35-dim vector)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="riskrule",
            name="category",
            field=models.CharField(
                choices=[
                    ("communicable", "Communicable"),
                    ("chronic", "Chronic"),
                    ("critical", "Critical"),
                    ("maternal", "Maternal"),
                    ("child", "Child"),
                    ("general", "General"),
                ],
                default="general",
                max_length=50,
            ),
        ),
    ]
