# Generated by Django 5.2.14 on 2026-06-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("risk_engine", "0007_add_feature_vector_and_child_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskassessment",
            name="hard_flag_category",
            field=models.CharField(
                blank=True,
                help_text="Denormalized category from hard_flag_rule",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="riskassessment",
            name="protocol_checklist",
            field=models.JSONField(blank=True, default=list, help_text="Action checklist steps [{hi, en}]"),
        ),
        migrations.CreateModel(
            name="HealthcareFacility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("name_hi", models.CharField(blank=True, max_length=200)),
                (
                    "facility_type",
                    models.CharField(
                        choices=[
                            ("phc", "Primary Health Centre"),
                            ("chc", "Community Health Centre"),
                            ("fru", "First Referral Unit"),
                            ("dh", "District Hospital"),
                            ("sdh", "Sub-Divisional Hospital"),
                            ("nrc", "Nutrition Rehabilitation Centre"),
                            ("awc", "Anganwadi Centre"),
                            ("vhsnd", "VHSN Day Site"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("region", models.CharField(blank=True, db_index=True, max_length=120)),
                (
                    "district",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("block", models.CharField(blank=True, db_index=True, max_length=120)),
                (
                    "village",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("address", models.TextField(blank=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["district", "block", "name"],
                "indexes": [
                    models.Index(
                        fields=["facility_type", "is_active"],
                        name="ix_facility_type_active",
                    ),
                    models.Index(fields=["district", "block"], name="ix_facility_geo"),
                ],
            },
        ),
    ]
